
= Key

[cols="1,3", options=header]
|===
|Value
|Description

|
{set:cellbgcolor:#FF0000}
Changes Required
|
{set:cellbgcolor!}
Indicates Changes Required for system stability, subscription compliance, or other reason.

|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|
{set:cellbgcolor!}
Indicates Changes Recommended to align with recommended practices, but not urgently required

|
{set:cellbgcolor:#A6B9BF}
N/A
|
{set:cellbgcolor!}
No advise given on line item.  For line items which are data-only to provide context.

|
{set:cellbgcolor:#80E5FF}
Advisory
|
{set:cellbgcolor!}
No change required or recommended, but additional information provided.

|
{set:cellbgcolor:#00FF00}
No Change
|
{set:cellbgcolor!}
No change required.  In alignment with recommended practices.

|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated
|
{set:cellbgcolor!}
Not yet evaluated.  Will appear only in draft copies.
|===

= Summary


[cols="1,2,2,3", options=header]
|===
|*Category*
|*Item Evaluated*
|*Observed Result*
|*Recommendation*


// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1010_compute-provider.item

// Category
|
{set:cellbgcolor!}
Infra

// Item Evaluated
a|
<<Infrastructure Provider(s)>>

| VSphere 

|
{set:cellbgcolor:#00FF00}
No Change



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1020_installation-type.item

// Category
|
{set:cellbgcolor!}
Infra

// Item Evaluated
a|
<<Installation Type>>

| OpenShift UPI is configured 

|
{set:cellbgcolor:#00FF00}
No Change



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1030_if-upi-is-customer-using-additional-machinesets.item

// Category
|
{set:cellbgcolor!}
Infra

// Item Evaluated
a|
<<Check if user-provisioned infrastructure (UPI) using additional MachineSets>>

| No additional MachineSet 

|
{set:cellbgcolor:#00FF00}
No Change



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1070_if-upi-what-kind-of-openshift-provisioning-automation-exists.item

// Category
|
{set:cellbgcolor!}
Infra

// Item Evaluated
a|
<<Check if user-provisioned infrastructure (UPI) OpenShift Provisioning Automation exists>>

| No additional MachineSet 

|
{set:cellbgcolor:#00FF00}
No Change



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1190_node_cpu_mem_storage.item

// Category
|
{set:cellbgcolor!}
Infra

// Item Evaluated
a|
<<OpenShift Node Status>>

| None 

|
{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END


// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1190_node_cpu_mem_storage.item

// Category
|
{set:cellbgcolor!}
Infra

// Item Evaluated
a|
<<OpenShift Node Usage>>

| Some node utilize more than 50% 

|
{set:cellbgcolor:#80E5FF}
Advisory


// ------------------------ITEM END



// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1040_vmware-version.item

// Category
|
{set:cellbgcolor!}
vSphere

// Item Evaluated
a|
VMware vSphere Version

| 8.0.1.22742005 

|
{set:cellbgcolor:#00FF00}
No Change



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1050_vcenter-highly-available.item

// Category
|
{set:cellbgcolor!}
vSphere

// Item Evaluated
a|
<<vCenter Highly Available>>

| vCenter Highly Available 

|
{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1060_vcenter-service-account.item

// Category
|
{set:cellbgcolor!}
vSphere

// Item Evaluated
a|
vCenter Service Account

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1080_physical-hypervisor-topology.item

// Category
|
{set:cellbgcolor!}
vSphere

// Item Evaluated
a|
<<Physical Hypervisor Topology>>

| Physical Hypervisor Topology is not set 

|
{set:cellbgcolor:#FEFE20}
Changes Recommended



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1090_node-placement-on-hosts.item

// Category
|
{set:cellbgcolor!}
vSphere

// Item Evaluated
a|
<<Node Placement on Hosts>>

| Master node is on a separate ESXi host 

|
{set:cellbgcolor:#00FF00}
No Change



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1100_vmware-datastore-storage-provider.item

// Category
|
{set:cellbgcolor!}
vSphere

// Item Evaluated
a|
Check to see if the OpenShift Cluster is configured to use VMware datastore

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1110_vmware-ha-enabled.item

// Category
|
{set:cellbgcolor!}
vSphere

// Item Evaluated
a|
<<vSphere HA Enabled>>

| vCenter Highly Available 

|
{set:cellbgcolor:#00FF00}
No Change



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1120_datastore-storage-provider.item

// Category
|
{set:cellbgcolor!}
vSphere

// Item Evaluated
a|
Datastore Storage Provider

| vSAN 

|
{set:cellbgcolor:#00FF00}
No Change



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1130_datastore-multitenancy.item

// Category
|
{set:cellbgcolor!}
vSphere

// Item Evaluated
a|
Datastore Multitenancy

| OpenShift use Shared DataStore 

|
{set:cellbgcolor:#FEFE20}
Changes Recommended



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1140_vmware-networking-type.item

// Category
|
{set:cellbgcolor!}
vSphere

// Item Evaluated
a|
VMware Networking Type

| DistributedVirtualPortgroup 

|
{set:cellbgcolor:#00FF00}
No Change



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1150_vmware-backup.item

// Category
|
{set:cellbgcolor!}
vSphere

// Item Evaluated
a|
VM Backup

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1160_vmware-time-synchronization-enabled.item

// Category
|
{set:cellbgcolor!}
vSphere

// Item Evaluated
a|
VMware Time Synchronization Enabled

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1170_node-network-ranges.item

// Category
|
{set:cellbgcolor!}
Network

// Item Evaluated
a|
Node Network Ranges

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/2010_node-network-topology.item

// Category
|
{set:cellbgcolor!}
Network

// Item Evaluated
a|
Node Network Topology

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/2020_mtu-sizes.item

// Category
|
{set:cellbgcolor!}
Network

// Item Evaluated
a|
Cluster Network MTU Size

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/2030_load-balancer-type.item

// Category
|
{set:cellbgcolor!}
Network

// Item Evaluated
a|
<<Load Balancer Type>>

||
{set:cellbgcolor:#FFFFFF}
To Be Evaluated





// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/2040_load-balancer-health-checks-enabled.item

// Category
|
{set:cellbgcolor!}
Network

// Item Evaluated
a|
<<Load Balancer Health Checks Enabled>>

||
{set:cellbgcolor:#FFFFFF}
To Be Evaluated





// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/2050_load-balancer-balancing-algorithm.item

// Category
|
{set:cellbgcolor!}
Network

// Item Evaluated
a|
<<Load Balancer Balancing Algorithm>>

||
{set:cellbgcolor:#FFFFFF}
To Be Evaluated





// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/2051_load-balancer-ssl-passthrough.item

// Category
|
{set:cellbgcolor!}
Network

// Item Evaluated
a|
<<Load Balancer SSL Settings>>

||
{set:cellbgcolor:#FFFFFF}
To Be Evaluated





// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/2052_load-balancer-vips_consistently_configured.item

// Category
|
{set:cellbgcolor!}
Network

// Item Evaluated
a|
<<Load Balancer VIPs Consistently Configured>>

||
{set:cellbgcolor:#FFFFFF}
To Be Evaluated





// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/2060_ingress-controller-type.item

// Category
|
{set:cellbgcolor!}
Network

// Item Evaluated
a|
<<Ingress Controller Type>>

| Default OpenShift ingress controller in use

|
{set:cellbgcolor:#00FF00}
No Change



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/2070_ingress-controller-placement.item

// Category
|
{set:cellbgcolor!}
Network

// Item Evaluated
a|
<<Ingress Controller Placement>>

| Ingress Controller Placement not set

|
{set:cellbgcolor:#FEFE20}
Changes Recommended



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/2080_ingress-controller-replica-count.item

// Category
|
{set:cellbgcolor!}
Network

// Item Evaluated
a|
<<Ingress Controller Replica Count>>

| Default OpenShift ingress replica not match

|
{set:cellbgcolor:#FEFE20}
Changes Recommended



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/2080_ingress-controller-replica-count.item

// Category
|
{set:cellbgcolor!}
Network

// Item Evaluated
a|
<<Ingress Controller Certificate>>

|Default wildcard certificate not configured

|
{set:cellbgcolor:#FEFE20}
Changes Recommended





// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/2090_openshift-sdn-plugin.item

// Category
|
{set:cellbgcolor!}
Network

// Item Evaluated
a|
<<CNI Network Plugin>>

| OpenShiftSDN

|
{set:cellbgcolor:#FEFE20}
Changes Recommended



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/3110_provider.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
Provider 1

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/3120_technology.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
Technology 1

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/3130_block-or-file.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
Block or File

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/3210_provider.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
Provider 2

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/3220_technology.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
Technology 2

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/3230_block-or-file.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
Block or File

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/3310_provider.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
Provider 3

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/3320_technology.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
Technology 3

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/3330_block-or-file.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
Block or File

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/3340_multipath-enabled.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
Multipath Enabled

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/3350_IQN_Set_Correctly.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
iSCSI Initiator Name

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4000_openshift_version.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Cluster Version>>

| 4.11.9

|
{set:cellbgcolor:#FEFE20}
Changes Recommended



// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4000_openshift_version.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|

<<Cluster Operators>>

| All CO operators Ready 

|
{set:cellbgcolor:#00FF00}
No Change



// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4001_masters_schedulable.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Control Nodes Schedulable>>

|Masters nodes are not Schedulable

|
{set:cellbgcolor:#00FF00}
No Change





// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4005_infra-nodes.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Infrastructure Nodes present>>

| Infra nodes not available, total: None

|
{set:cellbgcolor:#FEFE20}
Changes Recommended



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4009_default_scc.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Default Security Context Constraint>>

| SCC not modified 

|
{set:cellbgcolor:#FEFE20}
Changes Recommended



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4010_adequate-measures-in-place-to-keep-customer-workloads-off-infra-nodes.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Adequate Measures in place to keep customer workloads off Infra Nodes>>

| Infrastructure node with required taints not configured 

|
{set:cellbgcolor:#FF0000}
Changes Required



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4011_default_project_template_set.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Default Project Template Set>>

| No Default project template

|
{set:cellbgcolor:#FEFE20}
Changes Recommended



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4012_default_node_selector_set.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Default Node Selector Set>>

|Default Node Selector not Set

|
{set:cellbgcolor:#FEFE20}
Changes Recommended





// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4013_self_provisioner_enabled.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Self Provisioner Enabled>>

| Self Provisioner is not enabled 

|
{set:cellbgcolor:#FEFE20}
Changes Recommended



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4019_kubeadmin_enabled.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Kubeadmin user disabled>>

| Default OpenShift `kubeadmin` is present 

|
{set:cellbgcolor:#FF0000}
Changes Required



// ------------------------ITEM END


// ------------------------ITEM START


// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Network Policy>>

|Network Policies not enabled

|
{set:cellbgcolor:#FEFE20}
Changes Recommended





// ------------------------ITEM END


// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4020_identity-provider-type.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Identity Provider Type>>

|Identity Provider Type is not set

|
{set:cellbgcolor:#FF0000}
Changes Required




// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4030_identity-provider-search-url.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Identity Provider Search URL>>

|Identity Provider Type is not set

|
{set:cellbgcolor:#FFFFFF}
Not Applicable




// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4040_ldap-encrypted-connection.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<LDAP Encrypted Connection>>

|Identity Provider Type is not set

|
{set:cellbgcolor:#FFFFFF}
Not Applicable




// ------------------------ITEM END



// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4051_image-registry-internal.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Openshift internal registry is functioning and running>>

| Openshift internal registry is not functioning and running 

|
{set:cellbgcolor:#FF0000}
Changes Required



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4160_user-workload-monitoring.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<User Workload Monitoring>>

| User Workload Monitoring not Set 

|
{set:cellbgcolor:#FEFE20}
Changes Recommended



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4170_openshift-logging-installed.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<OpenShift Logging>>

| OpenShift Logging not configured 

|
{set:cellbgcolor:#FF0000}
Changes Required



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4171_alternative_log_aggregation.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Alternative Log Aggregation>>

|Not Applicable|
{set:cellbgcolor:#FFFFFF}
Not Applicable





// ------------------------ITEM END



// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4250_etcd-backup-defined.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
etcd backup defined

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4251_etcd-encryption.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<ETCD Encryption Enabled>>

| No ETCD encryption 

|
{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4252_etcd_disk_performance.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Etcd Performance>>

| ETCD is not healthy 

|
{set:cellbgcolor:#FF0000}
Changes Required



// ------------------------ITEM END



// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4260_infra-machine-configs-defined.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Infra machine config pool defined>>

| Infra machine config pool not defined

|
{set:cellbgcolor:#FEFE20}
Changes Recommended



// ------------------------ITEM END


// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4280_kubelet-config-overridden.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Kubelet Configuration Overridden>>

| Kubelet Configuration Overridden not configured

|
{set:cellbgcolor:#FEFE20}
Changes Recommended



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4290_emptydir-volumes-in-use.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<EmptyDir Volumes in use>>

| NA 

|
{set:cellbgcolor:#00FF00}
No Change



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4310_proxy-config.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Openshift Proxy Settings>>

|OpenShift Proxy setting is not set

|
{set:cellbgcolor:#FFFFFF}
Not Applicable





// ------------------------ITEM END



// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/5010_readiness-and-liveness-probes.item

// Category
|
{set:cellbgcolor!}
App Dev

// Item Evaluated
a|
<<Readiness and Liveness Probes>>

|Readiness and Liveness Probes not configured

|
{set:cellbgcolor:#FEFE20}
Changes Recommended





// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/5020_elevated-privileges.item

// Category
|
{set:cellbgcolor!}
App Dev

// Item Evaluated
a|
<<Elevated Privileges>>

| No user workload use Elevated Privileges in unprivileged way 

|
{set:cellbgcolor:#00FF00}
No Change



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/5030_limit-request-configured.item

// Category
|
{set:cellbgcolor!}
App Dev

// Item Evaluated
a|
<<Resource Quotas Defined>>

|Resource Requests and Limits not configured for user projects

|
{set:cellbgcolor:#FEFE20}
Changes Recommended





// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/5050_deployment-iac-items-versioned.item

// Category
|
{set:cellbgcolor!}
App Dev

// Item Evaluated
a|
Deployment IaC Items Versioned

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/5070_deployment-iac-type.item

// Category
|
{set:cellbgcolor!}
App Dev

// Item Evaluated
a|
Deployment IaC Type

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/5080_primary-ci-cd-tool.item

// Category
|
{set:cellbgcolor!}
App Dev

// Item Evaluated
a|
Primary CI CD Tool

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/5090_version-control.item

// Category
|
{set:cellbgcolor!}
App Dev

// Item Evaluated
a|
Version Control

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/5100_openshift-integration-method.item

// Category
|
{set:cellbgcolor!}
App Dev

// Item Evaluated
a|
OpenShift Integration Method

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/5110_container-registry-integration-method.item

// Category
|
{set:cellbgcolor!}
App Dev

// Item Evaluated
a|
Container Registry Integration Method

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END







// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/5150_container-base_images.item

// Category
|
{set:cellbgcolor!}
App Dev

// Item Evaluated
a|
Container Base Images

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/5160_disaster_recovery_deployments.item

// Category
|
{set:cellbgcolor!}
App Dev

// Item Evaluated
a|
Disaster Recovery Deployments

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END







// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/6070_rbac_is_enabled.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
Verify that RBAC is enabled

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END


// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/6110_garbage_collection.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<Ensure that garbage collection is configured as appropriate>>

| Garbage Collection configuration should be revised

|
{set:cellbgcolor:#FEFE20}
Changes Recommended



// ------------------------ITEM END


// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/6260_client_cert_authentication.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
Client certificate authentication should not be used for users

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END



// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/6310_external_secret_storage.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
Consider external secret storage

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END



// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/6540_CICD-scanning.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
CI/CD integration with Security Scanning

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END




// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/7010_logging-forward-audit.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<Forward OpenShift audit logs to external logging system>>

|Not Applicable|
{set:cellbgcolor:#FFFFFF}
Not Applicable




// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/7020_logging-forward-app.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<Forward OpenShift application logs to external logging system>>

|Not Applicable|
{set:cellbgcolor:#FFFFFF}
Not Applicable





// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/7030_logging-forward-infra.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<Forward OpenShift infrastructure logs to external logging system>>

|Not Applicable|
{set:cellbgcolor:#FFFFFF}
Not Applicable





// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/7050_logging-healthy.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<OpenShift logging deployment is functioning and healthy>>

|Not Applicable|
{set:cellbgcolor:#FFFFFF}
Not Applicable





// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/7060_logging-resource-contention.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<OpenShift logging Elasticsearch pods are scheduled on appropriate nodes>>

|Not Applicable|
{set:cellbgcolor:#FFFFFF}
Not Applicable





// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/7070_logging-elastic-log-size.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<OpenShift Logging Elasticsearch storage has sufficient space>>

|Not Applicable|
{set:cellbgcolor:#FFFFFF}
Not Applicable





// ------------------------ITEM END




// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/7130_monitoring-user-apps.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<Application specific metrics are monitored on OpenShift>>

| ServiceMonitors not configured 

|
{set:cellbgcolor:#FEFE20}
Changes Recommended



// ------------------------ITEM END



// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/7150_monitoring-alert-notify-external.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<Ensure OpenShift alerts are forwarded to an external system that is monitored>>

| OpenShift alerts are not forwarded to an external system

|
{set:cellbgcolor:#FF0000}
Changes Required



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/7160_monitoring-persistent-storage.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<Monitoring components need high performance/local persistent storage to maintain consistent state after a pod restart>>

| OpenShift monitoring components do not have the appropriate storage 

|
{set:cellbgcolor:#FF0000}
Changes Required



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/7170_team-skills.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
Team Skills Operating Openshift

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END
|===

<<<

{set:cellbgcolor!}

# Infrastructure


[cols="1,2,2,3", options=header]
|===
|*Category*
|*Item Evaluated*
|*Observed Result*
|*Recommendation*


// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1010_compute-provider.item

// Category
|
{set:cellbgcolor!}
Infra

// Item Evaluated
a|
<<Infrastructure Provider(s)>>

| VSphere 

|
{set:cellbgcolor:#00FF00}
No Change



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1020_installation-type.item

// Category
|
{set:cellbgcolor!}
Infra

// Item Evaluated
a|
<<Installation Type>>

| OpenShift UPI is configured 

|
{set:cellbgcolor:#00FF00}
No Change



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1030_if-upi-is-customer-using-additional-machinesets.item

// Category
|
{set:cellbgcolor!}
Infra

// Item Evaluated
a|
<<Check if user-provisioned infrastructure (UPI) using additional MachineSets>>

| No additional MachineSet 

|
{set:cellbgcolor:#00FF00}
No Change



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1070_if-upi-what-kind-of-openshift-provisioning-automation-exists.item

// Category
|
{set:cellbgcolor!}
Infra

// Item Evaluated
a|
<<Check if user-provisioned infrastructure (UPI) OpenShift Provisioning Automation exists>>

| No additional MachineSet 

|
{set:cellbgcolor:#00FF00}
No Change



// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1190_node_cpu_mem_storage.item

// Category
|
{set:cellbgcolor!}
Infra

// Item Evaluated
a|
<<OpenShift Node Status>>

| None 

|
{set:cellbgcolor:#00FF00}
No Change



// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1190_node_cpu_mem_storage.item

// Category
|
{set:cellbgcolor!}
Infra

// Item Evaluated
a|
<<OpenShift Node Usage>>

| Some node utilize more than 50% 

|
{set:cellbgcolor:#80E5FF}
Advisory



// ------------------------ITEM END

|===

<<<

== Infrastructure Provider(s)

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

**Observation**

Infrastructure Cloud Provider is VSphere

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/installing/index


== Installation Type

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

**Observation**

OpenShift installation Method is UPI

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/installing/index


== Check if user-provisioned infrastructure (UPI) using additional MachineSets

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

**Observation**

OpenShift installation Method is UPI and has no additional machineSet

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/installing/index


== Check if user-provisioned infrastructure (UPI) OpenShift Provisioning Automation exists

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

**Observation**

OpenShift installation Method is UPI and has no additional machineSet

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/installing/index


== OpenShift Node Status

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

[source, bash]
----
NAME                                 STATUS   ROLES    AGE   VERSION
master-0.n6n8k.dynamic.opentlc.com   Ready    master   15h   v1.24.0+dc5a2fd
master-1.n6n8k.dynamic.opentlc.com   Ready    master   15h   v1.24.0+dc5a2fd
master-2.n6n8k.dynamic.opentlc.com   Ready    master   15h   v1.24.0+dc5a2fd
worker-0.n6n8k.dynamic.opentlc.com   Ready    worker   14h   v1.24.0+dc5a2fd
worker-1.n6n8k.dynamic.opentlc.com   Ready    worker   14h   v1.24.0+dc5a2fd

----


**Observation**

All nodes are Ready. 

**Recommendation**

None 

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11

== OpenShift Node Usage

[cols="^"]
|===
|
{set:cellbgcolor:#80E5FF}
Advisory
|===

[source, bash]
----
NAME                                 CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
master-0.n6n8k.dynamic.opentlc.com   1405m        40%    11031Mi         74%       
master-1.n6n8k.dynamic.opentlc.com   834m         23%    6808Mi          46%       
master-2.n6n8k.dynamic.opentlc.com   674m         19%    7198Mi          48%       
worker-0.n6n8k.dynamic.opentlc.com   502m         33%    3482Mi          52%       
worker-1.n6n8k.dynamic.opentlc.com   537m         35%    3725Mi          55%       

----


**Observation**

Some node utilize more than 50% 

**Recommendation**

You require to add more resources to cluster nodes. 

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11

<<<

{set:cellbgcolor!}

# vSphere


[cols="1,2,2,3", options=header]
|===
|*Category*
|*Item Evaluated*
|*Observed Result*
|*Recommendation*


// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1040_vmware-version.item

// Category
|
{set:cellbgcolor!}
vSphere

// Item Evaluated
a|
VMware vSphere Version

| 8.0.1.22742005 

|
{set:cellbgcolor:#00FF00}
No Change



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1050_vcenter-highly-available.item

// Category
|
{set:cellbgcolor!}
vSphere

// Item Evaluated
a|
<<vCenter Highly Available>>

| vCenter Highly Available 

|
{set:cellbgcolor:#00FF00}
No Change



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1060_vcenter-service-account.item

// Category
|
{set:cellbgcolor!}
vSphere

// Item Evaluated
a|
vCenter Service Account

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1080_physical-hypervisor-topology.item

// Category
|
{set:cellbgcolor!}
vSphere

// Item Evaluated
a|
<<Physical Hypervisor Topology>>

| Physical Hypervisor Topology is not set 

|
{set:cellbgcolor:#FEFE20}
Changes Recommended



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1090_node-placement-on-hosts.item

// Category
|
{set:cellbgcolor!}
vSphere

// Item Evaluated
a|
<<Node Placement on Hosts>>

| Master node is on a separate ESXi host 

|
{set:cellbgcolor:#00FF00}
No Change



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1100_vmware-datastore-storage-provider.item

// Category
|
{set:cellbgcolor!}
vSphere

// Item Evaluated
a|
Check to see if the OpenShift Cluster is configured to use VMware datastore

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1110_vmware-ha-enabled.item

// Category
|
{set:cellbgcolor!}
vSphere

// Item Evaluated
a|
<<vSphere HA Enabled>>

| vCenter Highly Available 

|
{set:cellbgcolor:#00FF00}
No Change



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1120_datastore-storage-provider.item

// Category
|
{set:cellbgcolor!}
vSphere

// Item Evaluated
a|
Datastore Storage Provider

| vSAN 

|
{set:cellbgcolor:#00FF00}
No Change



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1130_datastore-multitenancy.item

// Category
|
{set:cellbgcolor!}
vSphere

// Item Evaluated
a|
Datastore Multitenancy

| OpenShift use Shared DataStore 

|
{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1140_vmware-networking-type.item

// Category
|
{set:cellbgcolor!}
vSphere

// Item Evaluated
a|
VMware Networking Type

| DistributedVirtualPortgroup 

|
{set:cellbgcolor:#00FF00}
No Change



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1150_vmware-backup.item

// Category
|
{set:cellbgcolor!}
vSphere

// Item Evaluated
a|
VM Backup

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1160_vmware-time-synchronization-enabled.item

// Category
|
{set:cellbgcolor!}
vSphere

// Item Evaluated
a|
VMware Time Synchronization Enabled

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END
|===

<<<


== vCenter Highly Available

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

**Observation**

vCenter Highly Available

**Recommendation**

None



== Physical Hypervisor Topology

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

**Observation**

ESXi hosts are not equally distributed across three failure domains. To ensure a better resilience in case of a datacenter partial disaster recovery, cusomter should ensure an equal distribution of the ESXi hosts in the failure domains. 

**Recommendation**

Troubleshoot why node is not Ready. 

*Reference Link(s)*

* https://cloud.redhat.com/blog/a-guide-to-implementing-failure-domains-with-openshift-workloads-on-vmware[Implementing Failure Domains with OpenShift Workloads on VMware]

== Node Placement on Hosts

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

**Observation**

Master node is on a separate ESXi host 

**Recommendation**

None 



== vSphere HA Enabled

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

**Observation**

vCenter Highly Available

**Recommendation**

None



== Datastore Multitenancy

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

**Observation**

Other workload machines share the same datastore for persistent storage.

**Recommendation**

Customer should consider to configure a separated datastore for each cluster to avoid operational issues if a datastore is full.








<<<

{set:cellbgcolor!}


# Network


[cols="1,2,2,3", options=header]
|===
|*Category*
|*Item Evaluated*
|*Observed Result*
|*Recommendation*


// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/1170_node-network-ranges.item

// Category
|
{set:cellbgcolor!}
Network

// Item Evaluated
a|
Node Network Ranges

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/2010_node-network-topology.item

// Category
|
{set:cellbgcolor!}
Network

// Item Evaluated
a|
Node Network Topology

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/2020_mtu-sizes.item

// Category
|
{set:cellbgcolor!}
Network

// Item Evaluated
a|
Cluster Network MTU Size

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/2030_load-balancer-type.item

// Category
|
{set:cellbgcolor!}
Network

// Item Evaluated
a|
<<Load Balancer Type>>

||
{set:cellbgcolor:#FFFFFF}
To Be Evaluated





// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/2040_load-balancer-health-checks-enabled.item

// Category
|
{set:cellbgcolor!}
Network

// Item Evaluated
a|
<<Load Balancer Health Checks Enabled>>

||
{set:cellbgcolor:#FFFFFF}
To Be Evaluated





// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/2050_load-balancer-balancing-algorithm.item

// Category
|
{set:cellbgcolor!}
Network

// Item Evaluated
a|
<<Load Balancer Balancing Algorithm>>

||
{set:cellbgcolor:#FFFFFF}
To Be Evaluated





// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/2051_load-balancer-ssl-passthrough.item

// Category
|
{set:cellbgcolor!}
Network

// Item Evaluated
a|
<<Load Balancer SSL Settings>>

||
{set:cellbgcolor:#FFFFFF}
To Be Evaluated





// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/2052_load-balancer-vips_consistently_configured.item

// Category
|
{set:cellbgcolor!}
Network

// Item Evaluated
a|
<<Load Balancer VIPs Consistently Configured>>

||
{set:cellbgcolor:#FFFFFF}
To Be Evaluated





// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/2060_ingress-controller-type.item

// Category
|
{set:cellbgcolor!}
Network

// Item Evaluated
a|
<<Ingress Controller Type>>

| Default OpenShift ingress controller in use

|
{set:cellbgcolor:#00FF00}
No Change



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/2070_ingress-controller-placement.item

// Category
|
{set:cellbgcolor!}
Network

// Item Evaluated
a|
<<Ingress Controller Placement>>

| Ingress Controller Placement not set

|
{set:cellbgcolor:#FEFE20}
Changes Recommended



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/2080_ingress-controller-replica-count.item

// Category
|
{set:cellbgcolor!}
Network

// Item Evaluated
a|
<<Ingress Controller Replica Count>>

| Default OpenShift ingress replica not match

|
{set:cellbgcolor:#FEFE20}
Changes Recommended



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/2080_ingress-controller-replica-count.item

// Category
|
{set:cellbgcolor!}
Network

// Item Evaluated
a|
<<Ingress Controller Certificate>>

|Default wildcard certificate not configured

|
{set:cellbgcolor:#FEFE20}
Changes Recommended





// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/2090_openshift-sdn-plugin.item

// Category
|
{set:cellbgcolor!}
Network

// Item Evaluated
a|
<<CNI Network Plugin>>

| OpenShiftSDN

|
{set:cellbgcolor:#FEFE20}
Changes Recommended



// ------------------------ITEM END
|===

<<<


== Load Balancer Type



**Observation**

To Be Evaluated

**Recommendation**

To Be Evaluated



== Load Balancer Health Checks Enabled



**Observation**

To Be Evaluated

**Recommendation**

To Be Evaluated



== Load Balancer Balancing Algorithm



**Observation**

To Be Evaluated

**Recommendation**

To Be Evaluated



== Load Balancer SSL Settings



**Observation**

To Be Evaluated

**Recommendation**

To Be Evaluated



== Load Balancer VIPs Consistently Configured



**Observation**

To Be Evaluated

**Recommendation**

To Be Evaluated



== Ingress Controller Type

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

[source, yaml]
----
ingresscontroller.operator.openshift.io/owning-ingresscontroller:default
----


**Observation**

Default OpenShift ingress controller in use

**Recommendation**

None. 

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/networking/index#configuring-ingress[Configure Ingress Controller]


== Ingress Controller Placement

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, bash]
----
NAME                              READY   STATUS    RESTARTS   AGE   IP               NODE                                 NOMINATED NODE   READINESS GATES
router-default-7bb945c647-9tx22   1/1     Running   0          15h   192.168.81.201   worker-1.n6n8k.dynamic.opentlc.com   <none>           <none>
router-default-7bb945c647-dsxpq   1/1     Running   0          15h   192.168.81.200   worker-0.n6n8k.dynamic.opentlc.com   <none>           <none>

----


**Observation**

Default OpenShift ingress Placement not set

**Recommendation**

OpenShift ingress pods should place on infra nodes. 

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/networking/index#configuring-ingress[Configure Ingress Controller]


== Ingress Controller Replica Count

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, bash]
----
NAME                              READY   STATUS    RESTARTS   AGE
router-default-7bb945c647-9tx22   1/1     Running   0          15h
router-default-7bb945c647-dsxpq   1/1     Running   0          15h

----


**Observation**

Default OpenShift ingress replica not match

**Recommendation**

OpenShift ingress pods should place distributed on infra nodes with replica count three (3). 

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/networking/index#configuring-ingress[Configure Ingress Controller]


== Ingress Controller Certificate

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===



**Observation**

Default wildcard certificate has self-singed certificate, expired or is not yet valid.

**Recommendation**

Replacing the default wildcard certificate with one that is issued by a public CA already included in the CA bundle as provided by the container userspace allows external clients to connect securely to applications running under the .apps sub-domain.

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/security_and_compliance/configuring-certificates#replacing-default-ingress_replacing-default-ingresss[Default Ingress Certificate]


== CNI Network Plugin

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, yaml]
----
apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: Network
  metadata:
    creationTimestamp: "2024-02-29T16:24:26Z"
    generation: 2
    name: cluster
    resourceVersion: "2878"
    uid: 3a5b2f43-86a4-4e60-a430-ae2562a90174
  spec:
    clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
    externalIP:
      policy: {}
    networkType: OpenShiftSDN
    serviceNetwork:
    - 172.30.0.0/16
  status:
    clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
    clusterNetworkMTU: 1450
    networkType: OpenShiftSDN
    serviceNetwork:
    - 172.30.0.0/16
kind: List
metadata:
  resourceVersion: ""

----


**Observation**

OVN Kubernetes is the default plugin at latest releases. Recommend to migrate to OVN Kubernetes.

**Recommendation**

OpenShift CNI Network Plugin is 

OpenShiftSDN, it recommended to utilize OVN CNI based for more features utilization.

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/networking/index#openshift-sdn-default-cni-network-provider[CNI Network Provider]


<<<

{set:cellbgcolor!}

# Storage


[cols="1,2,2,3", options=header]
|===
|*Category*
|*Item Evaluated*
|*Observed Result*
|*Recommendation*


// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/3110_provider.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
Provider 1

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/3120_technology.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
Technology 1

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/3130_block-or-file.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
Block or File

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/3210_provider.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
Provider 2

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/3220_technology.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
Technology 2

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/3230_block-or-file.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
Block or File

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/3310_provider.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
Provider 3

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/3320_technology.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
Technology 3

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/3330_block-or-file.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
Block or File

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/3340_multipath-enabled.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
Multipath Enabled

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/3350_IQN_Set_Correctly.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
iSCSI Initiator Name

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END
|===

<<<

<<<

{set:cellbgcolor!}

# OpenShift Cluster Config


[cols="1,2,2,3", options=header]
|===
|*Category*
|*Item Evaluated*
|*Observed Result*
|*Recommendation*


// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4000_openshift_version.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Cluster Version>>

| 4.11.9

|
{set:cellbgcolor:#FEFE20}
Changes Recommended



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4000_openshift_version.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Cluster Operators>>

| All CO operators Ready 

|
{set:cellbgcolor:#00FF00}
No Change



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4001_masters_schedulable.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Control Nodes Schedulable>>

|Masters nodes are not Schedulable

|
{set:cellbgcolor:#00FF00}
No Change





// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4005_infra-nodes.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Infrastructure Nodes present>>

| Infra nodes not available, total: None

|
{set:cellbgcolor:#FEFE20}
Changes Recommended



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4009_default_scc.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Default Security Context Constraint>>

| SCC not modified 

|
{set:cellbgcolor:#FEFE20}
Changes Recommended



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4010_adequate-measures-in-place-to-keep-customer-workloads-off-infra-nodes.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Adequate Measures in place to keep customer workloads off Infra Nodes>>

| Infrastructure node with required taints not configured 

|
{set:cellbgcolor:#FF0000}
Changes Required



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4011_default_project_template_set.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Default Project Template Set>>

| No Default project template

|
{set:cellbgcolor:#FEFE20}
Changes Recommended



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4012_default_node_selector_set.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Default Node Selector Set>>

|Default Node Selector not Set

|
{set:cellbgcolor:#FEFE20}
Changes Recommended





// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4013_self_provisioner_enabled.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Self Provisioner Enabled>>

| Self Provisioner is not enabled 

|
{set:cellbgcolor:#FEFE20}
Changes Recommended



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4019_kubeadmin_enabled.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Kubeadmin user disabled>>

| Default OpenShift `kubeadmin` is present 

|
{set:cellbgcolor:#FF0000}
Changes Required



// ------------------------ITEM END

// ------------------------ITEM START


// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Network Policy>>

|Network Policies not enabled

|
{set:cellbgcolor:#FEFE20}
Changes Recommended





// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4020_identity-provider-type.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Identity Provider Type>>

|Identity Provider Type is not set

|
{set:cellbgcolor:#FF0000}
Changes Required




// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4030_identity-provider-search-url.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Identity Provider Search URL>>

|Identity Provider Type is not set

|
{set:cellbgcolor:#FFFFFF}
Not Applicable




// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4040_ldap-encrypted-connection.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<LDAP Encrypted Connection>>

|Identity Provider Type is not set

|
{set:cellbgcolor:#FFFFFF}
Not Applicable




// ------------------------ITEM END


// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4051_image-registry-internal.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Openshift internal registry is functioning and running>>

| Openshift internal registry is not functioning and running 

|
{set:cellbgcolor:#FF0000}
Changes Required



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4160_user-workload-monitoring.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<User Workload Monitoring>>

| User Workload Monitoring not Set 

|
{set:cellbgcolor:#FEFE20}
Changes Recommended



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4170_openshift-logging-installed.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<OpenShift Logging>>

| OpenShift Logging not configured 

|
{set:cellbgcolor:#FF0000}
Changes Required



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4171_alternative_log_aggregation.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Alternative Log Aggregation>>

|Not Applicable|
{set:cellbgcolor:#FFFFFF}
Not Applicable





// ------------------------ITEM END



// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4250_etcd-backup-defined.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
etcd backup defined

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4251_etcd-encryption.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<ETCD Encryption Enabled>>

| No ETCD encryption 

|
{set:cellbgcolor:#FEFE20}
Changes Recommended




// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4252_etcd_disk_performance.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Etcd Performance>>

| ETCD is not healthy 

|
{set:cellbgcolor:#FF0000}
Changes Required


// ------------------------ITEM END



// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4260_infra-machine-configs-defined.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Infra machine config pool defined>>

| Infra machine config pool not defined

|
{set:cellbgcolor:#FEFE20}
Changes Recommended



// ------------------------ITEM END


// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4280_kubelet-config-overridden.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Kubelet Configuration Overridden>>

| Kubelet Configuration Overridden not configured

|
{set:cellbgcolor:#FEFE20}
Changes Recommended



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4290_emptydir-volumes-in-use.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<EmptyDir Volumes in use>>

| NA 

|
{set:cellbgcolor:#00FF00}
No Change



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/4310_proxy-config.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Openshift Proxy Settings>>

|OpenShift Proxy setting is not set

|
{set:cellbgcolor:#FFFFFF}
Not Applicable





// ------------------------ITEM END
|===

<<<


== Cluster Version

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, yaml]
----
apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: ClusterVersion
  metadata:
    creationTimestamp: "2024-02-29T16:24:30Z"
    generation: 2
    name: version
    resourceVersion: "322184"
    uid: f5e47723-3547-4d5a-be4a-01c68a7d2a00
  spec:
    channel: stable-4.11
    clusterID: f19bccb9-5116-4aaa-8bd7-8a15704ed5b8
  status:
    availableUpdates:
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:60091111bfb629d995977e4a91f090a2306e5be609d3a2652f31280ce0eea1f3
      url: https://access.redhat.com/errata/RHSA-2024:0682
      version: 4.11.58
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:e06117543fc10003c12017829bf7707fcc9f847c9aabcc7ac6150f7babf17ed1
      url: https://access.redhat.com/errata/RHSA-2024:0306
      version: 4.11.57
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:6fcfee1b6d7e4d2f9c0e05ec2b0ad159809ea93736ac0acdc710df0584510892
      url: https://access.redhat.com/errata/RHSA-2024:0059
      version: 4.11.56
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:5054bd54461e838f8ecf4a9b1c012cb38001ca79586bbd23e4db7041f2777a26
      url: https://access.redhat.com/errata/RHSA-2023:7691
      version: 4.11.55
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:f659402f24812b07e63e84901e79720650d1af4097535f059ce731031948a8a8
      url: https://access.redhat.com/errata/RHSA-2023:7479
      version: 4.11.54
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:ce532664d72d7b768ad61a83500e239f67a5d2aa2b62cb6a7caf90a8d3ed6e2e
      url: https://access.redhat.com/errata/RHSA-2023:6272
      version: 4.11.53
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:39d2479528d17b7b8a2238af4b0dfd69658b0f33edb416ed1ffb72bf6911befa
      url: https://access.redhat.com/errata/RHSA-2023:5697
      version: 4.11.52
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:57b4ea34db9f8ac57b3d796ae0e82e749d9a7708821364cc1770292586edfd87
      url: https://access.redhat.com/errata/RHBA-2023:5350
      version: 4.11.50
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:c0b6536214019f240004c1738e41c6f10f14599393eabada95eb32b2b79eee77
      url: https://access.redhat.com/errata/RHSA-2023:5001
      version: 4.11.49
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:08cd58a3f7f44512c69490126461fcc369877a98c8eb8807a92cf2dc54e60bd3
      url: https://access.redhat.com/errata/RHBA-2023:4752
      version: 4.11.48
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:bbed7981242fbc034a0e75ef265040137515da3756ac2eab9d2dd46348967c06
      url: https://access.redhat.com/errata/RHBA-2023:4614
      version: 4.11.47
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:88583eeaddcda4fbfdcf21f4dad86b01ff09bb010357c51f08fb24eb07fdb602
      url: https://access.redhat.com/errata/RHSA-2023:4310
      version: 4.11.46
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:c6771b12bd873c0e3e5fbc7afa600d92079de6534dcb52f09cb1d22ee49608a9
      url: https://access.redhat.com/errata/RHSA-2023:4053
      version: 4.11.45
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:52cbfbbeb9cc03b49c2788ac7333e63d3dae14673e01a9d8e59270f3a8390ed3
      url: https://access.redhat.com/errata/RHSA-2023:3915
      version: 4.11.44
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:d11cd63a623d33bda744f1a886d4b55710db4d68878967be2ebcd5535fafa25d
      url: https://access.redhat.com/errata/RHSA-2023:3542
      version: 4.11.43
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:518177a34452837920f1e77944f6afa08864537260c9f742b8c88b6157e4f901
      url: https://access.redhat.com/errata/RHSA-2023:3309
      version: 4.11.42
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:400267c7f4e61c6bfa0a59571467e8bd85c9188e442cbd820cc8263809be3775
      url: https://access.redhat.com/errata/RHBA-2023:3213
      version: 4.11.41
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:a6c98d2454e20cafe049972ff010262c54ea858256e6314ed7c777f266274959
      url: https://access.redhat.com/errata/RHBA-2023:2694
      version: 4.11.40
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:3545730c2018e0b092d6132b31068e517cbe99b99c52c54f2a9afad61e051e3d
      url: https://access.redhat.com/errata/RHSA-2023:2014
      version: 4.11.39
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:4f6089b62f54887ecc14684fafbe235a12f9d0c6b77379dee6ccc3675de6ed6d
      url: https://access.redhat.com/errata/RHBA-2023:1863
      version: 4.11.38
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:d06421d7594b65f775e2e7a8eabfef7bf2bcd0a357971ecdcd4edddaee6007e5
      url: https://access.redhat.com/errata/RHBA-2023:1760
      version: 4.11.37
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:ad9c84610d773f0fac61f51cf3589e6ab71eb8ce1af06c5bfc5c6acb67e8f326
      url: https://access.redhat.com/errata/RHBA-2023:1650
      version: 4.11.35
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:dbfa0881b5814ca79c1cd991fc890b666561b4ca58b3f673d79a31c900a0efbb
      url: https://access.redhat.com/errata/RHSA-2023:1504
      version: 4.11.34
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:225062eb681c09fc3e2856e04db95b76217b6a4bf3ac712033d1f04f7706dbf8
      url: https://access.redhat.com/errata/RHBA-2023:1396
      version: 4.11.33
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:2adcf72e10e67ace02ade32467ff7e75680ec1c71545a038196e569dc3149ad0
      url: https://access.redhat.com/errata/RHSA-2023:0245
      version: 4.11.25
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:36ee0fd41073248dc566350db67bd52d2bed6e1691ab11879379b462d740e721
      url: https://access.redhat.com/errata/RHSA-2023:0069
      version: 4.11.24
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:6e16fe4b05385d8422529c0120aff73f55a55eff57581a0714443d92a87f1ce9
      url: https://access.redhat.com/errata/RHBA-2023:0027
      version: 4.11.22
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:860cc37824074671c4cf76e02d224d243e670d2298e6dab8923ee391fbd0ae1c
      url: https://access.redhat.com/errata/RHSA-2022:9107
      version: 4.11.21
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:e86e058f7f66a687e273792f2e4ec70f3cc43ec9d2894bebee5caf5c4d4851a3
      url: https://access.redhat.com/errata/RHSA-2022:8893
      version: 4.11.20
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:22e149142517dfccb47be828f012659b1ccf71d26620e6f62468c264a7ce7863
      url: https://access.redhat.com/errata/RHBA-2022:8698
      version: 4.11.18
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:a4e3391f3ff6e33211a91ccd446f2dc57075301e3b974023172b8b8f6aac5461
      url: https://access.redhat.com/errata/RHBA-2022:8627
      version: 4.11.17
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:01c9ef7f802f0ba254847c22e960cd6453ed9f61d9296fdda8bd497712f53e23
      url: https://access.redhat.com/errata/RHSA-2022:8535
      version: 4.11.16
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:9ffb17b909a4fdef5324ba45ec6dd282985dd49d25b933ea401873183ef20bf8
      url: https://access.redhat.com/errata/RHBA-2022:7290
      version: 4.11.13
    - channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:0ca14e0f692391970fc23f88188f2a21f35a5ba24fe2f3cb908fd79fa46458e6
      url: https://access.redhat.com/errata/RHSA-2022:7201
      version: 4.11.12
    capabilities:
      enabledCapabilities:
      - baremetal
      - marketplace
      - openshift-samples
      knownCapabilities:
      - baremetal
      - marketplace
      - openshift-samples
    conditionalUpdates:
    - conditions:
      - lastTransitionTime: "2024-03-01T07:28:25Z"
        message: The update is recommended, because none of the conditional update
          risks apply to this cluster.
        reason: AsExpected
        status: "True"
        type: Recommended
      release:
        channels:
        - candidate-4.11
        - candidate-4.12
        - eus-4.12
        - fast-4.11
        - fast-4.12
        - stable-4.11
        - stable-4.12
        image: quay.io/openshift-release-dev/ocp-release@sha256:39d2479528d17b7b8a2238af4b0dfd69658b0f33edb416ed1ffb72bf6911befa
        url: https://access.redhat.com/errata/RHSA-2023:5697
        version: 4.11.52
      risks:
      - matchingRules:
        - promql:
            promql: |
              group(cluster_infrastructure_provider{type="BareMetal"})
              or
              0 * group(cluster_infrastructure_provider)
          type: PromQL
        message: The target release fails to provision and de-provision new baremetal
          machines required for scaling of a cluster.
        name: BrokenBaremetalProvisioning
        url: https://issues.redhat.com/browse/METAL-739
    - conditions:
      - lastTransitionTime: "2024-03-01T07:28:25Z"
        message: The 4.11.36 release only resolves an installation issue https://issues.redhat.com//browse/OCPBUGS-11663
          , which does not affect already running clusters. 4.11.36 does not include
          fixes delivered in recent 4.11.z releases and therefore upgrading from these
          versions would cause fixed bugs to reappear. Red Hat does not recommend
          upgrading clusters to 4.11.36 version for this reason. https://access.redhat.com/solutions/7007136
        reason: PatchesOlderRelease
        status: "False"
        type: Recommended
      release:
        channels:
        - candidate-4.11
        - candidate-4.12
        - eus-4.12
        - fast-4.11
        - fast-4.12
        - stable-4.11
        - stable-4.12
        image: quay.io/openshift-release-dev/ocp-release@sha256:8c04176b771a62abd801fcda3e952633566c8b5ff177b93592e8e8d2d1f8471d
        url: https://access.redhat.com/errata/RHBA-2023:1733
        version: 4.11.36
      risks:
      - matchingRules:
        - type: Always
        message: The 4.11.36 release only resolves an installation issue https://issues.redhat.com//browse/OCPBUGS-11663
          , which does not affect already running clusters. 4.11.36 does not include
          fixes delivered in recent 4.11.z releases and therefore upgrading from these
          versions would cause fixed bugs to reappear. Red Hat does not recommend
          upgrading clusters to 4.11.36 version for this reason.
        name: PatchesOlderRelease
        url: https://access.redhat.com/solutions/7007136
    - conditions:
      - lastTransitionTime: "2024-03-01T07:28:25Z"
        message: Machine Config Operator stalls when encountering orphaned KubeletConfig
          or ContainerRuntimeConfig resources. https://issues.redhat.com/browse/OCPNODE-1502
        reason: LeakedMachineConfigBlocksMCO
        status: "False"
        type: Recommended
      release:
        channels:
        - candidate-4.11
        - candidate-4.12
        - eus-4.12
        - fast-4.11
        - fast-4.12
        - stable-4.11
        - stable-4.12
        image: quay.io/openshift-release-dev/ocp-release@sha256:339bd66521b65b4bca329e8444661a0fbde8affe2f358ddc4ef938f2e3f55f4c
        url: https://access.redhat.com/errata/RHBA-2023:1296
        version: 4.11.32
      risks:
      - matchingRules:
        - type: Always
        message: Machine Config Operator stalls when encountering orphaned KubeletConfig
          or ContainerRuntimeConfig resources.
        name: LeakedMachineConfigBlocksMCO
        url: https://issues.redhat.com/browse/OCPNODE-1502
    - conditions:
      - lastTransitionTime: "2024-03-01T07:28:25Z"
        message: Machine Config Operator stalls when encountering orphaned KubeletConfig
          or ContainerRuntimeConfig resources. https://issues.redhat.com/browse/OCPNODE-1502
        reason: LeakedMachineConfigBlocksMCO
        status: "False"
        type: Recommended
      release:
        channels:
        - candidate-4.11
        - candidate-4.12
        - eus-4.12
        - fast-4.11
        - fast-4.12
        - stable-4.11
        - stable-4.12
        image: quay.io/openshift-release-dev/ocp-release@sha256:5fbe52f0f89d72e4d28b2a40dc69174fe10cce0a99dc5caa6fcfbf4226e08919
        url: https://access.redhat.com/errata/RHSA-2023:1158
        version: 4.11.31
      risks:
      - matchingRules:
        - type: Always
        message: Machine Config Operator stalls when encountering orphaned KubeletConfig
          or ContainerRuntimeConfig resources.
        name: LeakedMachineConfigBlocksMCO
        url: https://issues.redhat.com/browse/OCPNODE-1502
    - conditions:
      - lastTransitionTime: "2024-03-01T07:28:25Z"
        message: Machine Config Operator stalls when encountering orphaned KubeletConfig
          or ContainerRuntimeConfig resources. https://issues.redhat.com/browse/OCPNODE-1502
        reason: LeakedMachineConfigBlocksMCO
        status: "False"
        type: Recommended
      release:
        channels:
        - candidate-4.11
        - candidate-4.12
        - eus-4.12
        - fast-4.11
        - fast-4.12
        - stable-4.11
        - stable-4.12
        image: quay.io/openshift-release-dev/ocp-release@sha256:8230ca19fea80ef02f255a9f92688aa2639f68739a2b69114bf9af06080f9edc
        url: https://access.redhat.com/errata/RHSA-2023:1030
        version: 4.11.30
      risks:
      - matchingRules:
        - type: Always
        message: Machine Config Operator stalls when encountering orphaned KubeletConfig
          or ContainerRuntimeConfig resources.
        name: LeakedMachineConfigBlocksMCO
        url: https://issues.redhat.com/browse/OCPNODE-1502
    - conditions:
      - lastTransitionTime: "2024-03-01T07:28:25Z"
        message: Machine Config Operator stalls when encountering orphaned KubeletConfig
          or ContainerRuntimeConfig resources. https://issues.redhat.com/browse/OCPNODE-1502
        reason: LeakedMachineConfigBlocksMCO
        status: "False"
        type: Recommended
      release:
        channels:
        - candidate-4.11
        - candidate-4.12
        - eus-4.12
        - fast-4.11
        - fast-4.12
        - stable-4.11
        - stable-4.12
        image: quay.io/openshift-release-dev/ocp-release@sha256:1105aa27f627a99a2b3a8b6257a12697b2033a44f1fa2af41491a8e66cd279ac
        url: https://access.redhat.com/errata/RHSA-2023:0895
        version: 4.11.29
      risks:
      - matchingRules:
        - type: Always
        message: Machine Config Operator stalls when encountering orphaned KubeletConfig
          or ContainerRuntimeConfig resources.
        name: LeakedMachineConfigBlocksMCO
        url: https://issues.redhat.com/browse/OCPNODE-1502
    - conditions:
      - lastTransitionTime: "2024-03-01T07:28:25Z"
        message: Machine Config Operator stalls when encountering orphaned KubeletConfig
          or ContainerRuntimeConfig resources. https://issues.redhat.com/browse/OCPNODE-1502
        reason: LeakedMachineConfigBlocksMCO
        status: "False"
        type: Recommended
      release:
        channels:
        - candidate-4.11
        - candidate-4.12
        - eus-4.12
        - fast-4.11
        - fast-4.12
        - stable-4.11
        - stable-4.12
        image: quay.io/openshift-release-dev/ocp-release@sha256:85238bc3eddb88e958535597dbe8ec6f2aa88aa1713c2e1ee7faf88d1fefdac0
        url: https://access.redhat.com/errata/RHSA-2023:0774
        version: 4.11.28
      risks:
      - matchingRules:
        - type: Always
        message: Machine Config Operator stalls when encountering orphaned KubeletConfig
          or ContainerRuntimeConfig resources.
        name: LeakedMachineConfigBlocksMCO
        url: https://issues.redhat.com/browse/OCPNODE-1502
    - conditions:
      - lastTransitionTime: "2024-03-01T07:28:25Z"
        message: Machine Config Operator stalls when encountering orphaned KubeletConfig
          or ContainerRuntimeConfig resources. https://issues.redhat.com/browse/OCPNODE-1502
        reason: LeakedMachineConfigBlocksMCO
        status: "False"
        type: Recommended
      release:
        channels:
        - candidate-4.11
        - candidate-4.12
        - eus-4.12
        - fast-4.11
        - fast-4.12
        - stable-4.11
        - stable-4.12
        image: quay.io/openshift-release-dev/ocp-release@sha256:65e71a774a18c1c191f28655ce245abeecd653e8215b75f87eb23ceadacd530d
        url: https://access.redhat.com/errata/RHSA-2023:0651
        version: 4.11.27
      risks:
      - matchingRules:
        - type: Always
        message: Machine Config Operator stalls when encountering orphaned KubeletConfig
          or ContainerRuntimeConfig resources.
        name: LeakedMachineConfigBlocksMCO
        url: https://issues.redhat.com/browse/OCPNODE-1502
    - conditions:
      - lastTransitionTime: "2024-03-01T07:28:25Z"
        message: Machine Config Operator stalls when encountering orphaned KubeletConfig
          or ContainerRuntimeConfig resources. https://issues.redhat.com/browse/OCPNODE-1502
        reason: LeakedMachineConfigBlocksMCO
        status: "False"
        type: Recommended
      release:
        channels:
        - candidate-4.11
        - candidate-4.12
        - eus-4.12
        - fast-4.11
        - fast-4.12
        - stable-4.11
        - stable-4.12
        image: quay.io/openshift-release-dev/ocp-release@sha256:1c3913a65b0a10b4a0650f54e545fe928360a94767acea64c0bd10faa52c945a
        url: https://access.redhat.com/errata/RHSA-2023:0565
        version: 4.11.26
      risks:
      - matchingRules:
        - type: Always
        message: Machine Config Operator stalls when encountering orphaned KubeletConfig
          or ContainerRuntimeConfig resources.
        name: LeakedMachineConfigBlocksMCO
        url: https://issues.redhat.com/browse/OCPNODE-1502
    - conditions:
      - lastTransitionTime: "2024-03-01T07:28:25Z"
        message: 4.11.23 was replaced with 4.11.24. Please update to 4.11.24, it is
          an identical release except for the errata link. https://access.redhat.com/errata/RHSA-2023:0069
        reason: DuplicateRelease
        status: "False"
        type: Recommended
      release:
        channels:
        - candidate-4.11
        - candidate-4.12
        - eus-4.12
        - fast-4.11
        - fast-4.12
        - stable-4.11
        - stable-4.12
        image: quay.io/openshift-release-dev/ocp-release@sha256:24a273f879d6eed8d6cce1426798a623ebbe095e01a881e58aa78c4e9eff0c8b
        url: https://access.redhat.com/errata/RHBA-2023:0069
        version: 4.11.23
      risks:
      - matchingRules:
        - type: Always
        message: 4.11.23 was replaced with 4.11.24. Please update to 4.11.24, it is
          an identical release except for the errata link.
        name: DuplicateRelease
        url: https://access.redhat.com/errata/RHSA-2023:0069
    conditions:
    - lastTransitionTime: "2024-02-29T16:24:33Z"
      status: "True"
      type: RetrievedUpdates
    - lastTransitionTime: "2024-02-29T16:24:33Z"
      message: Kubernetes 1.25 and therefore OpenShift 4.12 remove several APIs which
        require admin consideration. Please see the knowledge article https://access.redhat.com/articles/6955381
        for details and instructions.
      reason: AdminAckRequired
      status: "False"
      type: Upgradeable
    - lastTransitionTime: "2024-02-29T16:24:33Z"
      message: Capabilities match configured spec
      reason: AsExpected
      status: "False"
      type: ImplicitlyEnabledCapabilities
    - lastTransitionTime: "2024-02-29T16:24:33Z"
      message: Payload loaded version="4.11.9" image="quay.io/openshift-release-dev/ocp-release@sha256:94b611f00f51c9acc44ca3f4634e46bd79d7d28b46047c7e3389d250698f0c99"
      reason: PayloadLoaded
      status: "True"
      type: ReleaseAccepted
    - lastTransitionTime: "2024-02-29T16:54:54Z"
      message: Done applying 4.11.9
      status: "True"
      type: Available
    - lastTransitionTime: "2024-02-29T16:54:54Z"
      status: "False"
      type: Failing
    - lastTransitionTime: "2024-02-29T16:54:54Z"
      message: Cluster version is 4.11.9
      status: "False"
      type: Progressing
    desired:
      channels:
      - candidate-4.11
      - candidate-4.12
      - eus-4.12
      - fast-4.11
      - fast-4.12
      - stable-4.11
      - stable-4.12
      image: quay.io/openshift-release-dev/ocp-release@sha256:94b611f00f51c9acc44ca3f4634e46bd79d7d28b46047c7e3389d250698f0c99
      url: https://access.redhat.com/errata/RHBA-2022:6897
      version: 4.11.9
    history:
    - completionTime: "2024-02-29T16:54:54Z"
      image: quay.io/openshift-release-dev/ocp-release@sha256:94b611f00f51c9acc44ca3f4634e46bd79d7d28b46047c7e3389d250698f0c99
      startedTime: "2024-02-29T16:24:33Z"
      state: Completed
      verified: false
      version: 4.11.9
    observedGeneration: 2
    versionHash: RWzQaCJG9xA=
kind: List
metadata:
  resourceVersion: ""

----


**Observation**

OpenShift version not the latest release

**Recommendation**

Update to latest release. 

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/updating_clusters/index


== Cluster Operators

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

[source, bash]
----
NAME                                       VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
authentication                             4.11.9    True        False         False      3h18m   
baremetal                                  4.11.9    True        False         False      15h     
cloud-controller-manager                   4.11.9    True        False         False      15h     
cloud-credential                           4.11.9    True        False         False      15h     
cluster-autoscaler                         4.11.9    True        False         False      15h     
config-operator                            4.11.9    True        False         False      15h     
console                                    4.11.9    True        False         False      14h     
csi-snapshot-controller                    4.11.9    True        False         False      15h     
dns                                        4.11.9    True        False         False      15h     
etcd                                       4.11.9    True        False         False      14h     
image-registry                             4.11.9    True        False         False      14h     
ingress                                    4.11.9    True        False         False      14h     
insights                                   4.11.9    True        False         False      14h     
kube-apiserver                             4.11.9    True        False         False      14h     
kube-controller-manager                    4.11.9    True        False         False      14h     
kube-scheduler                             4.11.9    True        False         False      14h     
kube-storage-version-migrator              4.11.9    True        False         False      15h     
machine-api                                4.11.9    True        False         False      14h     
machine-approver                           4.11.9    True        False         False      15h     
machine-config                             4.11.9    True        False         False      15h     
marketplace                                4.11.9    True        False         False      15h     
monitoring                                 4.11.9    True        False         False      14h     
network                                    4.11.9    True        False         False      15h     
node-tuning                                4.11.9    True        False         False      15h     
openshift-apiserver                        4.11.9    True        False         False      14h     
openshift-controller-manager               4.11.9    True        False         False      14h     
openshift-samples                          4.11.9    True        False         False      14h     
operator-lifecycle-manager                 4.11.9    True        False         False      15h     
operator-lifecycle-manager-catalog         4.11.9    True        False         False      15h     
operator-lifecycle-manager-packageserver   4.11.9    True        False         False      14h     
service-ca                                 4.11.9    True        False         False      15h     
storage                                    4.11.9    True        False         False      14h     

----


**Observation**

None

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11

== Control Nodes Schedulable

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

**Observation**

Masters nodes are not Schedulable. 

**Recommendation**

None.

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11html-single/nodes/index#working-with-nodes[Working with the nodes]


== Infrastructure Nodes present

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, bash]
----

----


**Observation**

Infrastructure nodes not configured. 

**Recommendation**

Infrastructure nodes allow customers to isolate infrastructure workloads for two primary purposes:

 1- to prevent incurring billing costs against subscription counts and
 2- to separate maintenance and management.

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11

* https://access.redhat.com/solutions/5034771[Infrastructure Nodes]

== Default Security Context Constraint

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, yaml]
----
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: null
apiVersion: security.openshift.io/v1
defaultAddCapabilities: null
fsGroup:
  type: MustRunAs
groups: []
kind: SecurityContextConstraints
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    kubernetes.io/description: restricted denies access to all host features and requires
      pods to be run with a UID, and SELinux context that are allocated to the namespace.
    release.openshift.io/create-only: "true"
  creationTimestamp: "2024-02-29T16:24:12Z"
  generation: 1
  name: restricted
  resourceVersion: "342"
  uid: eeef2900-15b0-4d36-a473-36e8a5e910e2
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities:
- KILL
- MKNOD
- SETUID
- SETGID
runAsUser:
  type: MustRunAsRange
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users: []
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret

----


**Observation**

OpenShift Default Security Context Constraint has been changed

**Recommendation**

Do not modify the default SCCs. Customizing the default SCCs can lead to issues when some of the platform pods deploy or OpenShift Container Platform is upgraded.Additionally, the default SCC values are reset to the defaults during some cluster upgrades, which discards all customizations to those SCCs.

Instead of modifying the default SCCs, create and modify your own SCCs as needed. For detailed steps, see Creating security context constraints.

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/authentication_and_authorization/index#managing-pod-security-policies[Default Security Context Constraint]


== Adequate Measures in place to keep customer workloads off Infra Nodes

[cols="^"]
|===
|
{set:cellbgcolor:#FF0000}
Changes Required
|===

**Observation**

No configuration or incomplete configuration is done to exclude application workloads from being scheduled in Infrastructure Nodes. This could lead to breach to subscription contract. 

**Recommendation**

Label and taint nodes designated for infrastructure. Ensure components such as the router, logging, and monitoring stacks have appropriate tolerances for these taints.

*Reference Link(s)*

* https://access.redhat.com/solutions/5034771


== Default Project Template Set

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, yaml]
----
apiVersion: config.openshift.io/v1
kind: Project
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
  creationTimestamp: "2024-02-29T16:25:08Z"
  generation: 1
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: f5e47723-3547-4d5a-be4a-01c68a7d2a00
  resourceVersion: "1617"
  uid: 8c2f911d-949f-4d12-9374-5d6982142b2a
spec: {}

----


**Observation**

No Default project template

**Recommendation**

Check in the reference how to create default project template. 

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/building_applications/index#configuring-project-creation[Configuring project creation]
* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/building_applications/index#quotas-setting-per-project[Quotas Setting Per Project]


== Default Node Selector Set

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

**Observation**

Default Node Selector not Set. 

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11html-single/nodes/index#nodes-scheduler-node-selectors-cluster_nodes-scheduler-node-selectors[Default Node Selector]


== Self Provisioner Enabled

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===
[source,bash]
----
Name:         self-provisioners
Labels:       <none>
Annotations:  rbac.authorization.kubernetes.io/autoupdate: true
Role:
  Kind:  ClusterRole
  Name:  self-provisioner
Subjects:
  Kind   Name                        Namespace
  ----   ----                        ---------
  Group  system:authenticated:oauth  

----


**Observation**

Self Provisioner is enabled for system:authenticated:oauth. Self Provisioner should be disabled to avoid uncontrolled namespace creation. 

**Recommendation**

Remove self-provisioner from the system:authenticated:oauth group

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/building_applications/index#disabling-project-self-provisioning_configuring-project-creation[Disabling project self-provisioning]


== Kubeadmin user disabled

[cols="^"]
|===
|
{set:cellbgcolor:#FF0000}
Changes Required
|===

[source, bash]
----
NAME        TYPE     DATA   AGE
kubeadmin   Opaque   1      15h

----


**Observation**

Kubeadmin user is not disabled 

**Recommendation**

This user is for temporary post installation steps and should be removed to avoid any potential security breach

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/authentication_and_authorization/removing-kubeadmin[Removing Kubeadmin user]


== Network Policy

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===
[source,bash]
----
# oc get netpol -A
No resources found
----


**Observation**

To isolate one or more pods in a project, you can create networkPolicy objects in that project to indicate the allowed incoming connections. 

**Recommendation**

Define network policies that restrict traffic to pods in your cluster.

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/networking/index#about-network-policy[About Network Policy]


== Identity Provider Type

[cols="^"]
|===
|
{set:cellbgcolor:#FF0000}
Changes Required
|===

**Observation**

There is no integration with a central identity provider (LDAP).

**Recommendation**

Integrate with an existing central identity provider such as Active Directory LDAP

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/authentication_and_authorization/index#configuring-ldap-identity-provider[Configuring an LDAP identity provider]




== Identity Provider Search URL

[cols="^"]
|===
|
{set:cellbgcolor:#FFFFFF}
Not Applicable
|===

**Observation**

There is no integration with a central identity provider (LDAP).

**Recommendation**

Integrate with an existing central identity provider such as Active Directory LDAP

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/authentication_and_authorization/index#configuring-ldap-identity-provider[Configuring an LDAP identity provider]




== LDAP Encrypted Connection

[cols="^"]
|===
|
{set:cellbgcolor:#FFFFFF}
Not Applicable
|===

**Observation**

There is no integration with a central identity provider (LDAP).

**Recommendation**

Integrate with an existing central identity provider such as Active Directory LDAP

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/authentication_and_authorization/index#configuring-ldap-identity-provider[Configuring an LDAP identity provider]


== Identity Provider Search URL


== Openshift internal registry is functioning and running

[cols="^"]
|===
|
{set:cellbgcolor:#FF0000}
Changes Required
|===

**Observation**

Openshift internal registry is functioning and running

**Recommendation**

Changes are required if the 'managementState' is not set to 'Managed'. 

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11html-single/registry/index[OpenShift registry]


== User Workload Monitoring

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

**Observation**

User workload monitoring is not configured.

**Recommendation**

Using this feature centralizes monitoring for core platform components and user-defined projects.

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11html-single/monitoring/configuring-the-monitoring-stack[Understanding the monitoring stack]
* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/monitoring/index#enabling-monitoring-for-user-defined-projects[Enabling monitoring for user-defined projects]

== OpenShift Logging

[cols="^"]
|===
|
{set:cellbgcolor:#FF0000}
Changes Required
|===

**Observation**

OpenShift Logging is not installed or configured. 

**Recommendation**

You need to deploy the logging subsystem to aggregate all the logs from your OpenShift Container Platform cluster, such as node system audit logs, application container logs, and infrastructure logs. 

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/logging/cluster-logging-deploying[Installing OpenShift Logging]
* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/logging/configuring-your-logging-deployment[Cluster Logging custom resource]
* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/logging/cluster-logging[Understanding Red Hat OpenShift Logging]


== Alternative Log Aggregation

[cols="^"]
|===
|
{set:cellbgcolor:#FFFFFF}
Not Applicable
|===

**Observation**

OpenShift Logging is not installed or configured. 

**Recommendation**

You need to deploy the logging subsystem to aggregate all the logs from your OpenShift Container Platform cluster, such as node system audit logs, application container logs, and infrastructure logs. 

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/logging/cluster-logging-deploying[Installing OpenShift Logging]
* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/logging/configuring-your-logging-deployment[Cluster Logging custom resource]
* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/logging/cluster-logging[Understanding Red Hat OpenShift Logging]


== ETCD Encryption Enabled

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, yaml]
----
apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: APIServer
  metadata:
    annotations:
      include.release.openshift.io/ibm-cloud-managed: "true"
      include.release.openshift.io/self-managed-high-availability: "true"
      include.release.openshift.io/single-node-developer: "true"
      oauth-apiserver.openshift.io/secure-token-storage: "true"
      release.openshift.io/create-only: "true"
    creationTimestamp: "2024-02-29T16:24:36Z"
    generation: 1
    name: cluster
    ownerReferences:
    - apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      name: version
      uid: f5e47723-3547-4d5a-be4a-01c68a7d2a00
    resourceVersion: "785"
    uid: 947082f9-a723-43ef-9cb3-f7cb417f8c87
  spec:
    audit:
      profile: Default
kind: List
metadata:
  resourceVersion: ""

----


**Observation**

No ETCD encryption

**Recommendation**

Check in the reference how to encrypt ETCD data. 

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/security_and_compliance/encrypting-etcd[ETCD Encryption]


== Etcd Performance

[cols="^"]
|===
|
{set:cellbgcolor:#FF0000}
Changes Required
|===



Reported etcd_disk_backend_commit_duration_seconds_bucket metric 10 minutes rate 99th percentile is more than 25ms.

Reported etcd_disk_wal_fsync_duration_seconds_bucket metric 10 minutes rate 99th percentile is more than 20ms.

Reported etcd_network_peer_round_trip_time_seconds_bucket metric 10 minutes rate 99th percentile is more than 50ms.

{endpoint="etcd-metrics", instance="192.168.81.102:9979", job="etcd", namespace="openshift-etcd", pod="etcd-master-2.n6n8k.dynamic.opentlc.com", service="etcd"} => 0.03055999999999994 @[1709278166.04]


**Observation**

ETCD is not healthy 

**Recommendation**

Check the reference for more details.
*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/scalability_and_performance/index#recommended-etcd-practices_recommended-host-practices[ETCD Recommended Practice]


== Infra machine config pool defined

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, bash]
----
NAME     CONFIG                                             UPDATED   UPDATING   DEGRADED   MACHINECOUNT   READYMACHINECOUNT   UPDATEDMACHINECOUNT   DEGRADEDMACHINECOUNT   AGE
master   rendered-master-28681326574294a0c37e66e6ef9a856d   True      False      False      3              3                   3                     0                      15h
worker   rendered-worker-071216cbf21bc04ab793be24fd595b29   True      False      False      2              2                   2                     0                      15h

----


**Observation**

Infra machine config pool not defined

**Recommendation**

In a production deployment, it is recommended that you deploy at least three machine sets to hold infrastructure components. Both OpenShift Logging and Red Hat OpenShift Service Mesh deploy Elasticsearch, which requires three instances to be installed on different nodes. Each of these nodes can be deployed to different availability zones for high availability.

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/machine_management/index#creating-infrastructure-machinesets


== Kubelet Configuration Overridden

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

**Observation**

Kubelet configuration is not enabled to provide garbage collection.

**Recommendation**

Configuring garbage collection for containers and images.

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/nodes/index#nodes-nodes-garbage-collection[Freeing Garbage Collection]


== EmptyDir Volumes in use

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

**Observation**

Application pods use persistent storage. 

**Recommendation**

NA. 

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11html-single/nodes/index#nodes-containers-volumes[Container Storage]


== Openshift Proxy Settings

[cols="^"]
|===
|
{set:cellbgcolor:#FFFFFF}
Not Applicable
|===
[source,bash]
----
apiVersion: config.openshift.io/v1
kind: Proxy
metadata:
  creationTimestamp: "2024-02-29T16:24:26Z"
  generation: 1
  name: cluster
  resourceVersion: "438"
  uid: 40704bc0-ba76-44ed-a299-313518cfe20d
spec:
  trustedCA:
    name: ""
status: {}

----


**Observation**

OpenShift Proxy setting is not set. 

**Recommendation**

None.




<<<

{set:cellbgcolor!}

# Application Development


[cols="1,2,2,3", options=header]
|===
|*Category*
|*Item Evaluated*
|*Observed Result*
|*Recommendation*




// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/5010_readiness-and-liveness-probes.item

// Category
|
{set:cellbgcolor!}
App Dev

// Item Evaluated
a|
<<Readiness and Liveness Probes>>

|Readiness and Liveness Probes not configured

|
{set:cellbgcolor:#FEFE20}
Changes Recommended





// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/5020_elevated-privileges.item

// Category
|
{set:cellbgcolor!}
App Dev

// Item Evaluated
a|
<<Elevated Privileges>>

| No user workload use Elevated Privileges in unprivileged way 

|
{set:cellbgcolor:#00FF00}
No Change



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/5030_limit-request-configured.item

// Category
|
{set:cellbgcolor!}
App Dev

// Item Evaluated
a|
<<Resource Quotas Defined>>

|Resource Requests and Limits not configured for user projects

|
{set:cellbgcolor:#FEFE20}
Changes Recommended




// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/5050_deployment-iac-items-versioned.item

// Category
|
{set:cellbgcolor!}
App Dev

// Item Evaluated
a|
Deployment IaC Items Versioned

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/5070_deployment-iac-type.item

// Category
|
{set:cellbgcolor!}
App Dev

// Item Evaluated
a|
Deployment IaC Type

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/5080_primary-ci-cd-tool.item

// Category
|
{set:cellbgcolor!}
App Dev

// Item Evaluated
a|
Primary CI CD Tool

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/5090_version-control.item

// Category
|
{set:cellbgcolor!}
App Dev

// Item Evaluated
a|
Version Control

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/5100_openshift-integration-method.item

// Category
|
{set:cellbgcolor!}
App Dev

// Item Evaluated
a|
OpenShift Integration Method

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/5110_container-registry-integration-method.item

// Category
|
{set:cellbgcolor!}
App Dev

// Item Evaluated
a|
Container Registry Integration Method

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END







// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/5150_container-base_images.item

// Category
|
{set:cellbgcolor!}
App Dev

// Item Evaluated
a|
Container Base Images

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/5160_disaster_recovery_deployments.item

// Category
|
{set:cellbgcolor!}
App Dev

// Item Evaluated
a|
Disaster Recovery Deployments

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END
|===

<<<

== Readiness and Liveness Probes

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===


=== What is a probe?

A probe is an OpenShift action that periodically performs diagnostics on a running container. Probes can be added in template or via console. There are three types of probes: Readiness, Liveness and Startup

Readiness Probe: Identifies when a container is able to handle external traffic received from a service. Even though the container is running it should not receive any requests.
**If the test fails for readiness probe the container will be taken out of service**.

Liveness Probe: Checks whether a pod is healthy by running a command or making a network request inside the container.
**If a test fails then the container is restarted**.

Startup Probe: Provides a way to defer the execution of liveness and readiness probes until a container indicates it is able to handle them. Kubernetes will not direct the other probe types to a container if it has a startup probe that has not yet succeeded.
**If a test fails then the container is restarted**.

OpenShift provided three options that control these probes:

1.  Open a TCP socket on the pod IP
2.  Perform an HTTP GET against a URL on a container that must return 200 OK
3.  Run a command in the container that must return exit code 0



**Observation**

Not all Deployments, DeploymentConfigs or StatefulSets specify Liveness, Readiness and Startup Probes. This could lead to running pods that are in an unhealthy state.
**Recommendation**

Developers involvement in creating the probes are important for the application's success.

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/building_applications/index#application-health[Application health]


== Elevated Privileges

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===



**Observation**

None

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/authentication_and_authorization/index#managing-pod-security-policies[Default Security Context Constraint]


== Resource Quotas Defined

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

**Observation**

Resource Requests and Limits not configured for user projects 

**Recommendation**

It is extremely important to create resource quotas and limits, particularly if horizontal pod autoscaling is to be used.

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/building_applications/index#quotas[Quotas]



<<<
{set:cellbgcolor!}

# Security


[cols="1,2,2,3", options=header]
|===
|*Category*
|*Item Evaluated*
|*Observed Result*
|*Recommendation*



// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/6070_rbac_is_enabled.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
Verify that RBAC is enabled

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END


// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/6110_garbage_collection.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<Ensure that garbage collection is configured as appropriate>>

| Garbage Collection configuration should be revised

|
{set:cellbgcolor:#FEFE20}
Changes Recommended



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/6260_client_cert_authentication.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
Client certificate authentication should not be used for users

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/6310_external_secret_storage.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
Consider external secret storage

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END


// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/6540_CICD-scanning.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
CI/CD integration with Security Scanning

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END



|===

<<<


== Ensure that garbage collection is configured as appropriate

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

**Observation**

Garbage Collection configuration is not enabled to provide garbage collection.

**Recommendation**

Configuring garbage collection for containers and images.

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/nodes/index#nodes-nodes-garbage-collection[Freeing Garbage Collection]






{set:cellbgcolor!}

# Operational Readiness


[cols="1,2,2,3", options=header]
|===
|*Category*
|*Item Evaluated*
|*Observed Result*
|*Recommendation*


// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/7010_logging-forward-audit.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<Forward OpenShift audit logs to external logging system>>

|Not Applicable|
{set:cellbgcolor:#FFFFFF}
Not Applicable





// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/7020_logging-forward-app.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<Forward OpenShift application logs to external logging system>>

|Not Applicable|
{set:cellbgcolor:#FFFFFF}
Not Applicable





// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/7030_logging-forward-infra.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<Forward OpenShift infrastructure logs to external logging system>>

|Not Applicable|
{set:cellbgcolor:#FFFFFF}
Not Applicable





// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/7050_logging-healthy.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<OpenShift logging deployment is functioning and healthy>>

|Not Applicable|
{set:cellbgcolor:#FFFFFF}
Not Applicable





// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/7060_logging-resource-contention.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<OpenShift logging Elasticsearch pods are scheduled on appropriate nodes>>

|Not Applicable|
{set:cellbgcolor:#FFFFFF}
Not Applicable





// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/7070_logging-elastic-log-size.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<OpenShift Logging Elasticsearch storage has sufficient space>>

|Not Applicable|
{set:cellbgcolor:#FFFFFF}
Not Applicable





// ------------------------ITEM END




// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/7130_monitoring-user-apps.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<Application specific metrics are monitored on OpenShift>>

| ServiceMonitors not configured 

|
{set:cellbgcolor:#FEFE20}
Changes Recommended



// ------------------------ITEM END



// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/7150_monitoring-alert-notify-external.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<Ensure OpenShift alerts are forwarded to an external system that is monitored>>

| OpenShift alerts are not forwarded to an external system

|
{set:cellbgcolor:#FF0000}
Changes Required



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/7160_monitoring-persistent-storage.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<Monitoring components need high performance/local persistent storage to maintain consistent state after a pod restart>>

| OpenShift monitoring components do not have the appropriate storage 

|
{set:cellbgcolor:#FF0000}
Changes Required



// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/7170_team-skills.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
Team Skills Operating Openshift

// Result
|


// Recommendation
|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated

// ------------------------ITEM END
|===

<<<

== Forward OpenShift audit logs to external logging system

[cols="^"]
|===
|
{set:cellbgcolor:#FFFFFF}
Not Applicable
|===

**Observation**

OpenShift Logging is not installed or configured. 

**Recommendation**

You need to deploy the logging subsystem to aggregate all the logs from your OpenShift Container Platform cluster, such as node system audit logs, application container logs, and infrastructure logs. 

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/logging/cluster-logging-deploying[Installing OpenShift Logging]
* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/logging/configuring-your-logging-deployment[Cluster Logging custom resource]
* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/logging/cluster-logging[Understanding Red Hat OpenShift Logging]


== Forward OpenShift application logs to external logging system

[cols="^"]
|===
|
{set:cellbgcolor:#FFFFFF}
Not Applicable
|===

**Observation**

OpenShift Logging is not installed or configured. 

**Recommendation**

You need to deploy the logging subsystem to aggregate all the logs from your OpenShift Container Platform cluster, such as node system audit logs, application container logs, and infrastructure logs. 

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/logging/cluster-logging-deploying[Installing OpenShift Logging]
* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/logging/configuring-your-logging-deployment[Cluster Logging custom resource]
* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/logging/cluster-logging[Understanding Red Hat OpenShift Logging]


== Forward OpenShift infrastructure logs to external logging system

[cols="^"]
|===
|
{set:cellbgcolor:#FFFFFF}
Not Applicable
|===

**Observation**

OpenShift Logging is not installed or configured. 

**Recommendation**

You need to deploy the logging subsystem to aggregate all the logs from your OpenShift Container Platform cluster, such as node system audit logs, application container logs, and infrastructure logs. 

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/logging/cluster-logging-deploying[Installing OpenShift Logging]
* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/logging/configuring-your-logging-deployment[Cluster Logging custom resource]
* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/logging/cluster-logging[Understanding Red Hat OpenShift Logging]


== OpenShift logging deployment is functioning and healthy

[cols="^"]
|===
|
{set:cellbgcolor:#FFFFFF}
Not Applicable
|===

**Observation**

OpenShift Logging is not installed or configured. 

**Recommendation**

You need to deploy the logging subsystem to aggregate all the logs from your OpenShift Container Platform cluster, such as node system audit logs, application container logs, and infrastructure logs. 

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/logging/cluster-logging-deploying[Installing OpenShift Logging]
* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/logging/configuring-your-logging-deployment[Cluster Logging custom resource]
* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/logging/cluster-logging[Understanding Red Hat OpenShift Logging]


== OpenShift logging Elasticsearch pods are scheduled on appropriate nodes

[cols="^"]
|===
|
{set:cellbgcolor:#FFFFFF}
Not Applicable
|===

**Observation**

OpenShift Logging is not installed or configured. 

**Recommendation**

You need to deploy the logging subsystem to aggregate all the logs from your OpenShift Container Platform cluster, such as node system audit logs, application container logs, and infrastructure logs. 

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/logging/cluster-logging-deploying[Installing OpenShift Logging]
* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/logging/configuring-your-logging-deployment[Cluster Logging custom resource]
* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/logging/cluster-logging[Understanding Red Hat OpenShift Logging]


== OpenShift Logging Elasticsearch storage has sufficient space

[cols="^"]
|===
|
{set:cellbgcolor:#FFFFFF}
Not Applicable
|===

**Observation**

OpenShift Logging is not installed or configured. 

**Recommendation**

You need to deploy the logging subsystem to aggregate all the logs from your OpenShift Container Platform cluster, such as node system audit logs, application container logs, and infrastructure logs. 

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/logging/cluster-logging-deploying[Installing OpenShift Logging]
* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/logging/configuring-your-logging-deployment[Cluster Logging custom resource]
* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/logging/cluster-logging[Understanding Red Hat OpenShift Logging]

[cols="^"]
|===
|
{set:cellbgcolor:#FF0000}
Changes Required
|===

**Observation**

OpenShift Logging is not installed or configured. 

**Recommendation**

You need to deploy the logging subsystem to aggregate all the logs from your OpenShift Container Platform cluster, such as node system audit logs, application container logs, and infrastructure logs. 

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/logging/cluster-logging-deploying[Installing OpenShift Logging]
* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/logging/configuring-your-logging-deployment[Cluster Logging custom resource]
* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/logging/cluster-logging[Understanding Red Hat OpenShift Logging]


== Application specific metrics are monitored on OpenShift

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

**Observation**

Insufficient tooling and processes are in place to ensure that applications deployed to OpenShift are performing as expected. 

**Recommendation**

OpenShift can monitor that application pods are started, and pass basic checks. Additional consideration should be given to capturing application specific metrics to identify performance and reliability issues for applications deployed to OCP. 

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11html-single/monitoring/index#managing-metrics[Managing Metrics]
* https://www.dynatrace.com/technologies/openshift-monitoring/[Monitor applications deployed to OpenShift using 3rd party tools such as Dynatrace]
* https://www.appdynamics.com/solutions/openshift[Monitor applications deployed to OpenShift using 3rd party tools such as AppDynamics]
* https://newrelic.com/blog/how-to-relic/red-hat-openshift-monitor[Monitor applications deployed to OpenShift using 3rd party tools such as NewRelic]


== Ensure OpenShift alerts are forwarded to an external system that is monitored

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

**Observation**

OpenShift alerts are not forwarded to an external system

**Recommendation**

Routing alerts to receivers enables you to send timely notifications to the appropriate teams when failures occur. 

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11monitoring/index#sending-notifications-to-external-systems_managing-alerts[Sending Notification to external system]


== Monitoring components need high performance/local persistent storage to maintain consistent state after a pod restart

[cols="^"]
|===
|
{set:cellbgcolor:#FF0000}
Changes Required
|===

**Observation**

The OpenShift monitoring components do not have the appropriate storage configured for a production environment and are not protected against data loss.

**Recommendation**

Configure persistent storage for the OpenShift monitoring components per the OpenShift documentation

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11html-single/monitoring/configuring-the-monitoring-stack[Understanding the monitoring stack]
* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11html-single/monitoring/index#configuring_persistent_storage_configuring-the-monitoring-stack[Monitoring Configuring persistent storage]








// Reset bgcolor for future tables
[grid=none,frame=none]
|===
|{set:cellbgcolor!}
|===

