= OpenShift Health Check Report

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Key

[cols="1,3", options=header]
|===
|Value
|Description

|
{set:cellbgcolor:#FF0000}
Changes Required
|
{set:cellbgcolor!}
Indicates Changes Required for system stability, subscription compliance, or other reason.

|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|
{set:cellbgcolor!}
Indicates Changes Recommended to align with recommended practices, but not urgently required

|
{set:cellbgcolor:#A6B9BF}
N/A
|
{set:cellbgcolor!}
No advise given on line item.  For line items which are data-only to provide context.

|
{set:cellbgcolor:#80E5FF}
Advisory
|
{set:cellbgcolor!}
No change required or recommended, but additional information provided.

|
{set:cellbgcolor:#00FF00}
No Change
|
{set:cellbgcolor!}
No change required. In alignment with recommended practices.

|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated
|
{set:cellbgcolor!}
Not yet evaluated. Will appear only in draft copies.
|===

= Summary


[cols="1,2,2,3", options=header]
|===
|*Category*
|*Item Evaluated*
|*Observed Result*
|*Recommendation*

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/cni-network-plugin.item

// Category
|
{set:cellbgcolor!}
Networking

// Item Evaluated
a|
<<CNI Network Plugin>>

| Cluster is using the recommended CNI network plugin: OVNKubernetes 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/network-policy.item

// Category
|
{set:cellbgcolor!}
Networking

// Item Evaluated
a|
<<Network Policy>>

| No network policies found in the cluster 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/ingress-controller.item

// Category
|
{set:cellbgcolor!}
Networking

// Item Evaluated
a|
<<Ingress Controller>>

| Ingress controller has 2 configuration issues 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/storage-classes.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
<<Storage Classes>>

| Default storage class 'gp3-csi' is configured, but no ReadWriteMany (RWX) capable storage class found 

|{set:cellbgcolor:#80E5FF}
Advisory


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/persistent-volumes.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
<<Persistent Volumes>>

| All 0 persistent volumes are healthy 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/storage-performance.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
<<Storage Performance>>

| No storage classes with explicit performance characteristics found 

|{set:cellbgcolor:#80E5FF}
Advisory


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/cluster-version.item

// Category
|
{set:cellbgcolor!}
Cluster

// Item Evaluated
a|
<<Cluster Version>>

| Cluster version 4.17.23 is up to date 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/cluster-operators.item

// Category
|
{set:cellbgcolor!}
Cluster

// Item Evaluated
a|
<<Cluster Operators>>

| All cluster operators are available 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/node-status.item

// Category
|
{set:cellbgcolor!}
Cluster

// Item Evaluated
a|
<<Node Status>>

| All 4 nodes are ready 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/node-usage.item

// Category
|
{set:cellbgcolor!}
Cluster

// Item Evaluated
a|
<<Node Usage>>

| All nodes are within resource usage thresholds 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/control-node-schedulable.item

// Category
|
{set:cellbgcolor!}
Cluster

// Item Evaluated
a|
<<Control Plane Node Schedulability>>

| All control plane nodes are properly configured to prevent regular workloads 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/infrastructure-nodes.item

// Category
|
{set:cellbgcolor!}
Cluster

// Item Evaluated
a|
<<Infrastructure Nodes>>

| No dedicated infrastructure nodes found 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/infra-machine-config-pool.item

// Category
|
{set:cellbgcolor!}
Cluster

// Item Evaluated
a|
<<Infrastructure Machine Config Pool>>

| No dedicated infrastructure machine config pool found 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/infrastructure-provider.item

// Category
|
{set:cellbgcolor!}
Cluster

// Item Evaluated
a|
<<Infrastructure Provider>>

| Infrastructure provider type: AWS 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/installation-type.item

// Category
|
{set:cellbgcolor!}
Cluster

// Item Evaluated
a|
<<Installation Type>>

| Installation type: Unknown 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/workload-off-infra-nodes.item

// Category
|
{set:cellbgcolor!}
Cluster

// Item Evaluated
a|
<<Workloads on Infrastructure Nodes>>

| No dedicated infrastructure nodes found in the cluster 

|{set:cellbgcolor:#A6B9BF}
Not Applicable


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/proxy-settings.item

// Category
|
{set:cellbgcolor!}
Cluster

// Item Evaluated
a|
<<OpenShift Proxy Settings>>

| OpenShift Proxy is not configured 

|{set:cellbgcolor:#A6B9BF}
Not Applicable


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/application-probes.item

// Category
|
{set:cellbgcolor!}
Applications

// Item Evaluated
a|
<<Application Probes>>

| Many user workloads are missing probes: 100.0% missing readiness probes, 50.0% missing liveness probes 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/resource-quotas.item

// Category
|
{set:cellbgcolor!}
Applications

// Item Evaluated
a|
<<Resource Quotas>>

| Only 0.0% of user namespaces (0 out of 2) have both resource quotas and limit ranges configured 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/emptydir-volumes.item

// Category
|
{set:cellbgcolor!}
Applications

// Item Evaluated
a|
<<EmptyDir Volumes>>

| No user workloads are using emptyDir volumes 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/cluster-default-scc.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<Default Security Context Constraint>>

| Default security context constraint (restricted) has not been modified 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/elevated-privileges.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<Elevated Privileges>>

| No user workloads using privileged containers were found 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/etcd-encryption.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<ETCD Encryption>>

| ETCD encryption is not enabled 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/etcd-backup.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<ETCD Backup>>

| No CronJobs found that might be backing up etcd 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/etcd-health.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<ETCD Health>>

| ETCD cluster is healthy 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/default-project-template.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<Default Project Template>>

| No default project template is configured 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/kubeadmin-user.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<Kubeadmin User>>

| The kubeadmin user has been removed 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/identity-provider.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<Identity Provider Configuration>>

| Identity providers are configured (HTPasswd), but no LDAP provider found 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/self-provisioner.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<Self Provisioner>>

| Self-provisioner role binding includes system:authenticated:oauth, allowing uncontrolled namespace creation 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/monitoring-storage.item

// Category
|
{set:cellbgcolor!}
Monitoring

// Item Evaluated
a|
<<Monitoring Storage>>

| OpenShift monitoring components do not have persistent storage configured 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/user-workload-monitoring.item

// Category
|
{set:cellbgcolor!}
Monitoring

// Item Evaluated
a|
<<User Workload Monitoring>>

| User workload monitoring is enabled 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/logging-install.item

// Category
|
{set:cellbgcolor!}
Monitoring

// Item Evaluated
a|
<<OpenShift Logging Installation>>

| OpenShift Logging is not installed 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/logging-health.item

// Category
|
{set:cellbgcolor!}
Monitoring

// Item Evaluated
a|
<<OpenShift Logging Health>>

| OpenShift Logging is not installed 

|{set:cellbgcolor:#A6B9BF}
Not Applicable


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/logging-storage.item

// Category
|
{set:cellbgcolor!}
Monitoring

// Item Evaluated
a|
<<OpenShift Logging Storage>>

| OpenShift Logging is not installed 

|{set:cellbgcolor:#A6B9BF}
Not Applicable


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/logging-forwarder.item

// Category
|
{set:cellbgcolor!}
Monitoring

// Item Evaluated
a|
<<Log Forwarding>>

| OpenShift Logging is not installed 

|{set:cellbgcolor:#A6B9BF}
Not Applicable


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/logging-placement.item

// Category
|
{set:cellbgcolor!}
Monitoring

// Item Evaluated
a|
<<Logging Component Placement>>

| OpenShift Logging is not installed 

|{set:cellbgcolor:#A6B9BF}
Not Applicable


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/service-monitors.item

// Category
|
{set:cellbgcolor!}
Monitoring

// Item Evaluated
a|
<<Service Monitors>>

| No ServiceMonitors found for application metrics monitoring 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END

|===

<<<

{set:cellbgcolor!}

# Networking

[cols="1,2,2,3", options=header]
|===
|*Category*
|*Item Evaluated*
|*Observed Result*
|*Recommendation*

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/cni-network-plugin.item

// Category
|
{set:cellbgcolor!}
Networking

// Item Evaluated
a|
<<CNI Network Plugin>>

| Cluster is using the recommended CNI network plugin: OVNKubernetes 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/network-policy.item

// Category
|
{set:cellbgcolor!}
Networking

// Item Evaluated
a|
<<Network Policy>>

| No network policies found in the cluster 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/ingress-controller.item

// Category
|
{set:cellbgcolor!}
Networking

// Item Evaluated
a|
<<Ingress Controller>>

| Ingress controller has 2 configuration issues 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END
|===

<<<

{set:cellbgcolor!}

# Storage

[cols="1,2,2,3", options=header]
|===
|*Category*
|*Item Evaluated*
|*Observed Result*
|*Recommendation*

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/storage-classes.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
<<Storage Classes>>

| Default storage class 'gp3-csi' is configured, but no ReadWriteMany (RWX) capable storage class found 

|{set:cellbgcolor:#80E5FF}
Advisory


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/persistent-volumes.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
<<Persistent Volumes>>

| All 0 persistent volumes are healthy 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/storage-performance.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
<<Storage Performance>>

| No storage classes with explicit performance characteristics found 

|{set:cellbgcolor:#80E5FF}
Advisory


// ------------------------ITEM END
|===

<<<

{set:cellbgcolor!}

# Cluster

[cols="1,2,2,3", options=header]
|===
|*Category*
|*Item Evaluated*
|*Observed Result*
|*Recommendation*

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/cluster-version.item

// Category
|
{set:cellbgcolor!}
Cluster

// Item Evaluated
a|
<<Cluster Version>>

| Cluster version 4.17.23 is up to date 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/cluster-operators.item

// Category
|
{set:cellbgcolor!}
Cluster

// Item Evaluated
a|
<<Cluster Operators>>

| All cluster operators are available 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/node-status.item

// Category
|
{set:cellbgcolor!}
Cluster

// Item Evaluated
a|
<<Node Status>>

| All 4 nodes are ready 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/node-usage.item

// Category
|
{set:cellbgcolor!}
Cluster

// Item Evaluated
a|
<<Node Usage>>

| All nodes are within resource usage thresholds 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/control-node-schedulable.item

// Category
|
{set:cellbgcolor!}
Cluster

// Item Evaluated
a|
<<Control Plane Node Schedulability>>

| All control plane nodes are properly configured to prevent regular workloads 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/infrastructure-nodes.item

// Category
|
{set:cellbgcolor!}
Cluster

// Item Evaluated
a|
<<Infrastructure Nodes>>

| No dedicated infrastructure nodes found 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/infra-machine-config-pool.item

// Category
|
{set:cellbgcolor!}
Cluster

// Item Evaluated
a|
<<Infrastructure Machine Config Pool>>

| No dedicated infrastructure machine config pool found 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/infrastructure-provider.item

// Category
|
{set:cellbgcolor!}
Cluster

// Item Evaluated
a|
<<Infrastructure Provider>>

| Infrastructure provider type: AWS 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/installation-type.item

// Category
|
{set:cellbgcolor!}
Cluster

// Item Evaluated
a|
<<Installation Type>>

| Installation type: Unknown 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/workload-off-infra-nodes.item

// Category
|
{set:cellbgcolor!}
Cluster

// Item Evaluated
a|
<<Workloads on Infrastructure Nodes>>

| No dedicated infrastructure nodes found in the cluster 

|{set:cellbgcolor:#A6B9BF}
Not Applicable


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/proxy-settings.item

// Category
|
{set:cellbgcolor!}
Cluster

// Item Evaluated
a|
<<OpenShift Proxy Settings>>

| OpenShift Proxy is not configured 

|{set:cellbgcolor:#A6B9BF}
Not Applicable


// ------------------------ITEM END
|===

<<<

{set:cellbgcolor!}

# Applications

[cols="1,2,2,3", options=header]
|===
|*Category*
|*Item Evaluated*
|*Observed Result*
|*Recommendation*

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/application-probes.item

// Category
|
{set:cellbgcolor!}
Applications

// Item Evaluated
a|
<<Application Probes>>

| Many user workloads are missing probes: 100.0% missing readiness probes, 50.0% missing liveness probes 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/resource-quotas.item

// Category
|
{set:cellbgcolor!}
Applications

// Item Evaluated
a|
<<Resource Quotas>>

| Only 0.0% of user namespaces (0 out of 2) have both resource quotas and limit ranges configured 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/emptydir-volumes.item

// Category
|
{set:cellbgcolor!}
Applications

// Item Evaluated
a|
<<EmptyDir Volumes>>

| No user workloads are using emptyDir volumes 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
|===

<<<

{set:cellbgcolor!}

# Security

[cols="1,2,2,3", options=header]
|===
|*Category*
|*Item Evaluated*
|*Observed Result*
|*Recommendation*

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/cluster-default-scc.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<Default Security Context Constraint>>

| Default security context constraint (restricted) has not been modified 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/elevated-privileges.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<Elevated Privileges>>

| No user workloads using privileged containers were found 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/etcd-encryption.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<ETCD Encryption>>

| ETCD encryption is not enabled 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/etcd-backup.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<ETCD Backup>>

| No CronJobs found that might be backing up etcd 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/etcd-health.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<ETCD Health>>

| ETCD cluster is healthy 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/default-project-template.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<Default Project Template>>

| No default project template is configured 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/kubeadmin-user.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<Kubeadmin User>>

| The kubeadmin user has been removed 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/identity-provider.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<Identity Provider Configuration>>

| Identity providers are configured (HTPasswd), but no LDAP provider found 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/self-provisioner.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<Self Provisioner>>

| Self-provisioner role binding includes system:authenticated:oauth, allowing uncontrolled namespace creation 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END
|===

<<<

{set:cellbgcolor!}

# Monitoring

[cols="1,2,2,3", options=header]
|===
|*Category*
|*Item Evaluated*
|*Observed Result*
|*Recommendation*

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/monitoring-storage.item

// Category
|
{set:cellbgcolor!}
Monitoring

// Item Evaluated
a|
<<Monitoring Storage>>

| OpenShift monitoring components do not have persistent storage configured 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/user-workload-monitoring.item

// Category
|
{set:cellbgcolor!}
Monitoring

// Item Evaluated
a|
<<User Workload Monitoring>>

| User workload monitoring is enabled 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/logging-install.item

// Category
|
{set:cellbgcolor!}
Monitoring

// Item Evaluated
a|
<<OpenShift Logging Installation>>

| OpenShift Logging is not installed 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/logging-health.item

// Category
|
{set:cellbgcolor!}
Monitoring

// Item Evaluated
a|
<<OpenShift Logging Health>>

| OpenShift Logging is not installed 

|{set:cellbgcolor:#A6B9BF}
Not Applicable


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/logging-storage.item

// Category
|
{set:cellbgcolor!}
Monitoring

// Item Evaluated
a|
<<OpenShift Logging Storage>>

| OpenShift Logging is not installed 

|{set:cellbgcolor:#A6B9BF}
Not Applicable


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/logging-forwarder.item

// Category
|
{set:cellbgcolor!}
Monitoring

// Item Evaluated
a|
<<Log Forwarding>>

| OpenShift Logging is not installed 

|{set:cellbgcolor:#A6B9BF}
Not Applicable


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/logging-placement.item

// Category
|
{set:cellbgcolor!}
Monitoring

// Item Evaluated
a|
<<Logging Component Placement>>

| OpenShift Logging is not installed 

|{set:cellbgcolor:#A6B9BF}
Not Applicable


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/service-monitors.item

// Category
|
{set:cellbgcolor!}
Monitoring

// Item Evaluated
a|
<<Service Monitors>>

| No ServiceMonitors found for application metrics monitoring 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END
|===

<<<

{set:cellbgcolor!}

== CNI Network Plugin

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

[source, bash]
----
apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: Network
  metadata:
    creationTimestamp: "2025-04-13T07:54:28Z"
    generation: 3
    name: cluster
    resourceVersion: "22751"
    uid: a5de3c40-77c4-4c7c-9e15-e7f69a0c6404
  spec:
    clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
    externalIP:
      policy: {}
    networkDiagnostics:
      mode: ""
      sourcePlacement: {}
      targetPlacement: {}
    networkType: OVNKubernetes
    serviceNetwork:
    - 172.30.0.0/16
  status:
    clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
    clusterNetworkMTU: 8901
    conditions:
    - lastTransitionTime: "2025-04-13T08:28:50Z"
      message: ""
      observedGeneration: 0
      reason: AsExpected
      status: "True"
      type: NetworkDiagnosticsAvailable
    networkType: OVNKubernetes
    serviceNetwork:
    - 172.30.0.0/16
kind: List
metadata:
  resourceVersion: ""

----

**Observation**

Cluster is using the recommended CNI network plugin: OVNKubernetes

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== Network Policy

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, bash]
----
No network policies configured
----

**Observation**

No network policies found in the cluster

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== Ingress Controller

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, bash]
----
Issues:
Ingress controller is not placed on dedicated infrastructure nodes
Ingress controller has insufficient replicas: 2 (recommended: >= 3)

apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  creationTimestamp: "2025-04-13T08:02:45Z"
  finalizers:
  - ingresscontroller.operator.openshift.io/finalizer-ingresscontroller
  generation: 2
  name: default
  namespace: openshift-ingress-operator
  resourceVersion: "29011"
  uid: 4b51055a-aec8-4cea-9045-e97d939c1e14
spec:
  clientTLS:
    clientCA:
      name: ""
    clientCertificatePolicy: ""
  defaultCertificate:
    name: cert-manager-ingress-cert
  httpCompression: {}
  httpEmptyRequestsPolicy: Respond
  httpErrorCodePages:
    name: ""
  replicas: 2
  tuningOptions:
    reloadInterval: 0s
  unsupportedConfigOverrides: null
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2025-04-13T08:02:46Z"
    reason: Valid
    status: "True"
    type: Admitted
  - lastTransitionTime: "2025-04-13T08:21:47Z"
    message: The deployment has Available status condition set to True
    reason: DeploymentAvailable
    status: "True"
    type: DeploymentAvailable
  - lastTransitionTime: "2025-04-13T08:21:47Z"
    message: Minimum replicas requirement is met
    reason: DeploymentMinimumReplicasMet
    status: "True"
    type: DeploymentReplicasMinAvailable
  - lastTransitionTime: "2025-04-13T08:44:28Z"
    message: All replicas are available
    reason: DeploymentReplicasAvailable
    status: "True"
    type: DeploymentReplicasAllAvailable
  - lastTransitionTime: "2025-04-13T08:44:28Z"
    message: Deployment is not actively rolling out
    reason: DeploymentNotRollingOut
    status: "False"
    type: DeploymentRollingOut
  - lastTransitionTime: "2025-04-13T08:02:46Z"
    message: The endpoint publishing strategy supports a managed load balancer
    reason: WantedByEndpointPublishingStrategy
    status: "True"
    type: LoadBalancerManaged
  - lastTransitionTime: "2025-04-13T08:02:48Z"
    message: The LoadBalancer service is provisioned
    reason: LoadBalancerProvisioned
    status: "True"
    type: LoadBalancerReady
  - lastTransitionTime: "2025-04-13T08:02:46Z"
    message: LoadBalancer is not progressing
    reason: LoadBalancerNotProgressing
    status: "False"
    type: LoadBalancerProgressing
  - lastTransitionTime: "2025-04-13T08:02:46Z"
    message: DNS management is supported and zones are specified in the cluster DNS
      config.
    reason: Normal
    status: "True"
    type: DNSManaged
  - lastTransitionTime: "2025-04-13T08:03:36Z"
    message: The record is provisioned in all reported zones.
    reason: NoFailedZones
    status: "True"
    type: DNSReady
  - lastTransitionTime: "2025-04-13T08:21:47Z"
    status: "True"
    type: Available
  - lastTransitionTime: "2025-04-13T08:44:28Z"
    status: "False"
    type: Progressing
  - lastTransitionTime: "2025-04-13T08:21:47Z"
    status: "False"
    type: Degraded
  - lastTransitionTime: "2025-04-13T08:02:46Z"
    message: IngressController is upgradeable.
    reason: Upgradeable
    status: "True"
    type: Upgradeable
  - lastTransitionTime: "2025-04-13T08:02:46Z"
    message: No evaluation condition is detected.
    reason: NoEvaluationCondition
    status: "False"
    type: EvaluationConditionsDetected
  - lastTransitionTime: "2025-04-13T08:21:47Z"
    message: Canary route checks for the default ingress controller are successful
    reason: CanaryChecksSucceeding
    status: "True"
    type: CanaryChecksSucceeding
  domain: apps.cluster-6cxmx.6cxmx.sandbox2376.opentlc.com
  endpointPublishingStrategy:
    loadBalancer:
      dnsManagementPolicy: Managed
      providerParameters:
        aws:
          classicLoadBalancer:
            connectionIdleTimeout: 0s
          type: Classic
        type: AWS
      scope: External
    type: LoadBalancerService
  observedGeneration: 2
  selector: ingresscontroller.operator.openshift.io/deployment-ingresscontroller=default
  tlsProfile:
    ciphers:
    - ECDHE-ECDSA-AES128-GCM-SHA256
    - ECDHE-RSA-AES128-GCM-SHA256
    - ECDHE-ECDSA-AES256-GCM-SHA384
    - ECDHE-RSA-AES256-GCM-SHA384
    - ECDHE-ECDSA-CHACHA20-POLY1305
    - ECDHE-RSA-CHACHA20-POLY1305
    - DHE-RSA-AES128-GCM-SHA256
    - DHE-RSA-AES256-GCM-SHA384
    - TLS_AES_128_GCM_SHA256
    - TLS_AES_256_GCM_SHA384
    - TLS_CHACHA20_POLY1305_SHA256
    minTLSVersion: VersionTLS12

----

**Observation**

Ingress controller has 2 configuration issues

**Recommendation**

Configure the ingress controller to run on dedicated infrastructure nodes

Refer to https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/html-single/networking/index#nw-ingress-controller-configuration-parameters_configuring-ingress

Increase the number of ingress controller replicas to at least 3 for high availability

Refer to https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/html-single/networking/index#configuring-ingress

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== Storage Classes

[cols="^"]
|===
|
{set:cellbgcolor:#80E5FF}
Advisory
|===

[source, bash]
----
Available storage classes:
gp2-csi, gp3-csi

Detailed output:
NAME                PROVISIONER       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2-csi             ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   169m
gp3-csi (default)   ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   169m

----

**Observation**

Default storage class 'gp3-csi' is configured, but no ReadWriteMany (RWX) capable storage class found

**Recommendation**

Consider adding a storage class that supports ReadWriteMany access mode for shared storage needs

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== Persistent Volumes

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

**Observation**

All 0 persistent volumes are healthy

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== Storage Performance

[cols="^"]
|===
|
{set:cellbgcolor:#80E5FF}
Advisory
|===

[source, bash]
----
Storage Class Details:
apiVersion: v1
items:
- allowVolumeExpansion: true
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    creationTimestamp: "2025-04-13T08:02:16Z"
    name: gp2-csi
    resourceVersion: "5953"
    uid: 16e400cf-2bc4-439e-89da-38641f2cf419
  parameters:
    encrypted: "true"
    type: gp2
  provisioner: ebs.csi.aws.com
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer
- allowVolumeExpansion: true
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
    creationTimestamp: "2025-04-13T08:02:16Z"
    name: gp3-csi
    resourceVersion: "5949"
    uid: 8103f5a6-95c0-4796-9c37-8d2d210e21e9
  parameters:
    encrypted: "true"
    type: gp3
  provisioner: ebs.csi.aws.com
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer
kind: List
metadata:
  resourceVersion: ""

----

**Observation**

No storage classes with explicit performance characteristics found

**Recommendation**

Consider defining storage classes with different performance tiers

Label storage classes with performance characteristics for better workload placement

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== Cluster Version

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

[source, bash]
----
apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: ClusterVersion
  metadata:
    creationTimestamp: "2025-04-13T07:54:32Z"
    generation: 2
    name: version
    resourceVersion: "30890"
    uid: 34bdd9cd-2ad6-4996-b4cd-21f09f96a111
  spec:
    channel: stable-4.17
    clusterID: 7c74295f-6c40-4d88-9d1f-7da121d26360
  status:
    availableUpdates: null
    capabilities:
      enabledCapabilities:
      - Build
      - CSISnapshot
      - CloudControllerManager
      - CloudCredential
      - Console
      - DeploymentConfig
      - ImageRegistry
      - Ingress
      - Insights
      - MachineAPI
      - NodeTuning
      - OperatorLifecycleManager
      - Storage
      - baremetal
      - marketplace
      - openshift-samples
      knownCapabilities:
      - Build
      - CSISnapshot
      - CloudControllerManager
      - CloudCredential
      - Console
      - DeploymentConfig
      - ImageRegistry
      - Ingress
      - Insights
      - MachineAPI
      - NodeTuning
      - OperatorLifecycleManager
      - Storage
      - baremetal
      - marketplace
      - openshift-samples
    conditions:
    - lastTransitionTime: "2025-04-13T07:54:57Z"
      status: "True"
      type: RetrievedUpdates
    - lastTransitionTime: "2025-04-13T07:54:57Z"
      message: Capabilities match configured spec
      reason: AsExpected
      status: "False"
      type: ImplicitlyEnabledCapabilities
    - lastTransitionTime: "2025-04-13T07:54:57Z"
      message: Payload loaded version="4.17.23" image="quay.io/openshift-release-dev/ocp-release@sha256:7e8b4557c0a15765440c543ab50cd591bb94f0745c20564e5f15d57bf5f76a82"
        architecture="amd64"
      reason: PayloadLoaded
      status: "True"
      type: ReleaseAccepted
    - lastTransitionTime: "2025-04-13T08:28:50Z"
      message: Done applying 4.17.23
      status: "True"
      type: Available
    - lastTransitionTime: "2025-04-13T08:51:50Z"
      status: "False"
      type: Failing
    - lastTransitionTime: "2025-04-13T08:28:50Z"
      message: Cluster version is 4.17.23
      status: "False"
      type: Progressing
    desired:
      channels:
      - candidate-4.17
      - candidate-4.18
      - eus-4.18
      - fast-4.17
      - fast-4.18
      - stable-4.17
      - stable-4.18
      image: quay.io/openshift-release-dev/ocp-release@sha256:7e8b4557c0a15765440c543ab50cd591bb94f0745c20564e5f15d57bf5f76a82
      url: https://access.redhat.com/errata/RHSA-2025:3297
      version: 4.17.23
    history:
    - completionTime: "2025-04-13T08:28:50Z"
      image: quay.io/openshift-release-dev/ocp-release@sha256:7e8b4557c0a15765440c543ab50cd591bb94f0745c20564e5f15d57bf5f76a82
      startedTime: "2025-04-13T07:54:57Z"
      state: Completed
      verified: false
      version: 4.17.23
    observedGeneration: 2
    versionHash: H9tjXrL6NpQ=
kind: List
metadata:
  resourceVersion: ""

----

**Observation**

Cluster version 4.17.23 is up to date

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== Cluster Operators

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

[source, bash]
----
NAME                                       VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
authentication                             4.17.23   True        False         False      124m    
baremetal                                  4.17.23   True        False         False      169m    
cloud-controller-manager                   4.17.23   True        False         False      172m    
cloud-credential                           4.17.23   True        False         False      175m    
cluster-autoscaler                         4.17.23   True        False         False      169m    
config-operator                            4.17.23   True        False         False      169m    
console                                    4.17.23   True        False         False      127m    
control-plane-machine-set                  4.17.23   True        False         False      169m    
csi-snapshot-controller                    4.17.23   True        False         False      169m    
dns                                        4.17.23   True        False         False      168m    
etcd                                       4.17.23   True        False         False      167m    
image-registry                             4.17.23   True        False         False      158m    
ingress                                    4.17.23   True        False         False      150m    
insights                                   4.17.23   True        False         False      163m    
kube-apiserver                             4.17.23   True        False         False      158m    
kube-controller-manager                    4.17.23   True        False         False      166m    
kube-scheduler                             4.17.23   True        False         False      163m    
kube-storage-version-migrator              4.17.23   True        False         False      169m    
machine-api                                4.17.23   True        False         False      158m    
machine-approver                           4.17.23   True        False         False      169m    
machine-config                             4.17.23   True        False         False      169m    
marketplace                                4.17.23   True        False         False      169m    
monitoring                                 4.17.23   True        False         False      149m    
network                                    4.17.23   True        False         False      171m    
node-tuning                                4.17.23   True        False         False      158m    
openshift-apiserver                        4.17.23   True        False         False      149m    
openshift-controller-manager               4.17.23   True        False         False      150m    
openshift-samples                          4.17.23   True        False         False      150m    
operator-lifecycle-manager                 4.17.23   True        False         False      169m    
operator-lifecycle-manager-catalog         4.17.23   True        False         False      169m    
operator-lifecycle-manager-packageserver   4.17.23   True        False         False      160m    
service-ca                                 4.17.23   True        False         False      169m    
storage                                    4.17.23   True        False         False      167m    

----

**Observation**

All cluster operators are available

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== Node Status

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

[source, bash]
----
NAME                                        STATUS   ROLES                  AGE    VERSION
ip-10-0-34-160.eu-west-1.compute.internal   Ready    worker                 158m   v1.30.10
ip-10-0-37-145.eu-west-1.compute.internal   Ready    control-plane,master   173m   v1.30.10
ip-10-0-46-210.eu-west-1.compute.internal   Ready    worker                 162m   v1.30.10
ip-10-0-57-153.eu-west-1.compute.internal   Ready    worker                 158m   v1.30.10

----

**Observation**

All 4 nodes are ready

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== Node Usage

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

[source, bash]
----
NAME                                        CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
ip-10-0-34-160.eu-west-1.compute.internal   260m         1%     3052Mi          4%        
ip-10-0-37-145.eu-west-1.compute.internal   711m         4%     8206Mi          13%       
ip-10-0-46-210.eu-west-1.compute.internal   159m         1%     2085Mi          3%        
ip-10-0-57-153.eu-west-1.compute.internal   266m         1%     2961Mi          4%        

----

**Observation**

All nodes are within resource usage thresholds

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== Control Plane Node Schedulability

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

[source, bash]
----
NAME                                        STATUS   ROLES                  AGE    VERSION    INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                                                KERNEL-VERSION                 CONTAINER-RUNTIME
ip-10-0-37-145.eu-west-1.compute.internal   Ready    control-plane,master   173m   v1.30.10   10.0.37.145   <none>        Red Hat Enterprise Linux CoreOS 417.94.202503241418-0   5.14.0-427.62.1.el9_4.x86_64   cri-o://1.30.11-2.rhaos4.17.git9e4d86d.el9

----

**Observation**

All control plane nodes are properly configured to prevent regular workloads

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== Infrastructure Nodes

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

**Observation**

No dedicated infrastructure nodes found

**Recommendation**

Configure dedicated infrastructure nodes

Infrastructure nodes allow you to isolate infrastructure workloads to prevent incurring billing costs against subscription counts and to separate maintenance and management

Refer to https://access.redhat.com/solutions/5034771

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== Infrastructure Machine Config Pool

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, bash]
----
NAME     CONFIG                                             UPDATED   UPDATING   DEGRADED   MACHINECOUNT   READYMACHINECOUNT   UPDATEDMACHINECOUNT   DEGRADEDMACHINECOUNT   AGE
master   rendered-master-43070e1234554ed0b7d22afef78e494a   True      False      False      1              1                   1                     0                      169m
worker   rendered-worker-c80ef53ecd38c6108f6ec39f470524c1   True      False      False      3              3                   3                     0                      169m

----

**Observation**

No dedicated infrastructure machine config pool found

**Recommendation**

Create a dedicated infrastructure machine config pool

In a production deployment, it is recommended that you deploy at least three machine sets to hold infrastructure components

Refer to https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/html-single/machine_management/index#creating-infrastructure-machinesets

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== Infrastructure Provider

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

[source, bash]
----
apiVersion: config.openshift.io/v1
kind: Infrastructure
metadata:
  creationTimestamp: "2025-04-13T07:54:26Z"
  generation: 1
  name: cluster
  resourceVersion: "518"
  uid: 799fb4b5-c590-4fd6-bc8a-3961410c0a1c
spec:
  cloudConfig:
    key: config
    name: cloud-provider-config
  platformSpec:
    aws: {}
    type: AWS
status:
  apiServerInternalURI: https://api-int.cluster-6cxmx.6cxmx.sandbox2376.opentlc.com:6443
  apiServerURL: https://api.cluster-6cxmx.6cxmx.sandbox2376.opentlc.com:6443
  controlPlaneTopology: SingleReplica
  cpuPartitioning: None
  etcdDiscoveryDomain: ""
  infrastructureName: cluster-6cxmx-7kpxc
  infrastructureTopology: HighlyAvailable
  platform: AWS
  platformStatus:
    aws:
      region: eu-west-1
    type: AWS

----

**Observation**

Infrastructure provider type: AWS

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== Installation Type

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

[source, bash]
----
Infrastructure Name: cluster-6cxmx-7kpxc

apiVersion: config.openshift.io/v1
kind: Infrastructure
metadata:
  creationTimestamp: "2025-04-13T07:54:26Z"
  generation: 1
  name: cluster
  resourceVersion: "518"
  uid: 799fb4b5-c590-4fd6-bc8a-3961410c0a1c
spec:
  cloudConfig:
    key: config
    name: cloud-provider-config
  platformSpec:
    aws: {}
    type: AWS
status:
  apiServerInternalURI: https://api-int.cluster-6cxmx.6cxmx.sandbox2376.opentlc.com:6443
  apiServerURL: https://api.cluster-6cxmx.6cxmx.sandbox2376.opentlc.com:6443
  controlPlaneTopology: SingleReplica
  cpuPartitioning: None
  etcdDiscoveryDomain: ""
  infrastructureName: cluster-6cxmx-7kpxc
  infrastructureTopology: HighlyAvailable
  platform: AWS
  platformStatus:
    aws:
      region: eu-west-1
    type: AWS

----

**Observation**

Installation type: Unknown

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== Workloads on Infrastructure Nodes

[cols="^"]
|===
|
{set:cellbgcolor:#A6B9BF}
Not Applicable
|===

**Observation**

No dedicated infrastructure nodes found in the cluster

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== OpenShift Proxy Settings

[cols="^"]
|===
|
{set:cellbgcolor:#A6B9BF}
Not Applicable
|===

[source, bash]
----
apiVersion: config.openshift.io/v1
kind: Proxy
metadata:
  creationTimestamp: "2025-04-13T07:54:28Z"
  generation: 1
  name: cluster
  resourceVersion: "537"
  uid: 79d324a3-fe9c-40da-a1d5-0857714e5530
spec:
  trustedCA:
    name: ""
status: {}

----

**Observation**

OpenShift Proxy is not configured

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== Application Probes

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, bash]
----
Summary:
- Total user workloads: 2
- Workloads missing readiness probes: 2 (100.0%)
- Workloads missing liveness probes: 1 (50.0%)
- Workloads missing both probes: 1 (50.0%)

Affected namespaces:
- cert-manager

Affected workloads:
- Deployment 'cert-manager' in namespace 'cert-manager' is missing readiness probe
- Deployment 'cert-manager-cainjector' in namespace 'cert-manager' is missing both readiness and liveness probes


What are Readiness and Liveness Probes?

Readiness Probe: Determines if a container is ready to accept traffic. When a pod's readiness check fails, it is removed from service load balancers.

Liveness Probe: Determines if a container is still running as expected. When a liveness check fails, Kubernetes will restart the container.

Benefits of using probes:
- Prevents traffic from being sent to unready containers
- Automatically restarts unhealthy containers
- Improves application resilience and availability
- Facilitates smoother deployments and updates
- Provides better visibility into application health

----

**Observation**

Many user workloads are missing probes: 100.0% missing readiness probes, 50.0% missing liveness probes

**Recommendation**

Configure readiness and liveness probes for all user workloads

Follow the Kubernetes documentation on pod lifecycle and probes: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== Resource Quotas

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, bash]
----
Summary:
- Total user namespaces: 2
- Namespaces with resource quotas: 0 (0.0%)
- Namespaces with limit ranges: 0 (0.0%)
- Namespaces with both: 0 (0.0%)

Namespaces without resource quotas:
- cert-manager
- cert-manager-operator

Namespaces without limit ranges:
- cert-manager
- cert-manager-operator

Namespaces without both:
- cert-manager
- cert-manager-operator


What are Resource Quotas and Limit Ranges?

Resource Quotas: Define the total amount of resources a namespace can use. They limit the total CPU, memory, and other resources that can be consumed by all pods in a namespace.

Limit Ranges: Define default resource limits and requests for containers in a namespace. They can also enforce minimum and maximum resource usage limits.

Benefits of using Resource Quotas and Limit Ranges:
- Prevent resource starvation by limiting the total resources a namespace can consume
- Ensure fair resource allocation across namespaces
- Protect against runaway applications that might consume all available resources
- Enforce resource constraints and prevent resource leaks
- Help with capacity planning and cost management

----

**Observation**

Only 0.0% of user namespaces (0 out of 2) have both resource quotas and limit ranges configured

**Recommendation**

Configure resource quotas and limit ranges for all user namespaces

Follow the Kubernetes documentation on resource quotas: https://kubernetes.io/docs/concepts/policy/resource-quotas/

Follow the Kubernetes documentation on limit ranges: https://kubernetes.io/docs/concepts/policy/limit-range/

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== EmptyDir Volumes

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

**Observation**

No user workloads are using emptyDir volumes

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== Default Security Context Constraint

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

[source, bash]
----
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: null
apiVersion: security.openshift.io/v1
defaultAddCapabilities: null
fsGroup:
  type: MustRunAs
groups: []
kind: SecurityContextConstraints
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    kubernetes.io/description: restricted denies access to all host features and requires
      pods to be run with a UID, and SELinux context that are allocated to the namespace.
    release.openshift.io/create-only: "true"
  creationTimestamp: "2025-04-13T07:54:14Z"
  generation: 1
  name: restricted
  resourceVersion: "409"
  uid: f8ccecb2-f20f-4054-9aed-2f90953a497c
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities:
- KILL
- MKNOD
- SETUID
- SETGID
runAsUser:
  type: MustRunAsRange
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users: []
volumes:
- configMap
- csi
- downwardAPI
- emptyDir
- ephemeral
- persistentVolumeClaim
- projected
- secret

----

**Observation**

Default security context constraint (restricted) has not been modified

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== Elevated Privileges

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

**Observation**

No user workloads using privileged containers were found

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== ETCD Encryption

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, bash]
----
apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: APIServer
  metadata:
    annotations:
      include.release.openshift.io/ibm-cloud-managed: "true"
      include.release.openshift.io/self-managed-high-availability: "true"
      oauth-apiserver.openshift.io/secure-token-storage: "true"
      release.openshift.io/create-only: "true"
    creationTimestamp: "2025-04-13T07:54:58Z"
    generation: 1
    name: cluster
    ownerReferences:
    - apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      name: version
      uid: 34bdd9cd-2ad6-4996-b4cd-21f09f96a111
    resourceVersion: "808"
    uid: 372dd50d-975d-4f0c-ae8a-1a6e5efe7f3a
  spec:
    audit:
      profile: Default
kind: List
metadata:
  resourceVersion: ""

----

**Observation**

ETCD encryption is not enabled

**Recommendation**

Enable etcd encryption to protect sensitive data

Follow the documentation at https://docs.openshift.com/container-platform/latest/security/encrypting-etcd.html

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== ETCD Backup

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, bash]
----
ETCD Cluster Operator status:
NAME   VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
etcd   4.17.23   True        False         False      167m    

----

**Observation**

No CronJobs found that might be backing up etcd

**Recommendation**

Set up regular etcd backups to protect against data loss

Follow the documentation at https://docs.openshift.com/container-platform/latest/backup_and_restore/control_plane_backup_and_restore/backing-up-etcd.html

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== ETCD Health

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

[source, bash]
----
ETCD Operator Information:
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  creationTimestamp: "2025-04-13T07:54:57Z"
  generation: 1
  name: etcd
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: 34bdd9cd-2ad6-4996-b4cd-21f09f96a111
  resourceVersion: "30158"
  uid: 51ec0b92-2098-4379-9708-8cdf5ec6a12a
spec: {}
status:
  conditions:
  - lastTransitionTime: "2025-04-13T08:19:20Z"
    message: |-
      NodeControllerDegraded: All master nodes are ready
      EtcdMembersDegraded: No unhealthy members found
    reason: AsExpected
    status: "False"
    type: Degraded
  - lastTransitionTime: "2025-04-13T08:19:20Z"
    message: |-
      NodeInstallerProgressing: 1 node is at revision 4
      EtcdMembersProgressing: No unstarted etcd members found
    reason: AsExpected
    status: "False"
    type: Progressing
  - lastTransitionTime: "2025-04-13T08:04:10Z"
    message: |-
      StaticPodsAvailable: 1 nodes are active; 1 node is at revision 4
      EtcdMembersAvailable: 1 members are available
    reason: AsExpected
    status: "True"
    type: Available
  - lastTransitionTime: "2025-04-13T08:02:10Z"
    message: All is well
    reason: AsExpected
    status: "True"
    type: Upgradeable
  - lastTransitionTime: "2025-04-13T08:02:10Z"
    reason: NoData
    status: Unknown
    type: EvaluationConditionsDetected
  extension: null
  relatedObjects:
  - group: operator.openshift.io
    name: cluster
    resource: etcds
  - group: ""
    name: openshift-config
    resource: namespaces
  - group: ""
    name: openshift-config-managed
    resource: namespaces
  - group: ""
    name: openshift-etcd-operator
    resource: namespaces
  - group: ""
    name: openshift-etcd
    resource: namespaces
  versions:
  - name: raw-internal
    version: 4.17.23
  - name: operator
    version: 4.17.23
  - name: etcd
    version: 4.17.23


ETCD Pods Information:
NAME                                             READY   STATUS    RESTARTS   AGE
etcd-ip-10-0-37-145.eu-west-1.compute.internal   4/4     Running   0          152m

----

**Observation**

ETCD cluster is healthy

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== Default Project Template

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, bash]
----
apiVersion: config.openshift.io/v1
kind: Project
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/create-only: "true"
  creationTimestamp: "2025-04-13T07:55:16Z"
  generation: 1
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: 34bdd9cd-2ad6-4996-b4cd-21f09f96a111
  resourceVersion: "1621"
  uid: f4856665-a2ef-4e1e-92f6-d296169ecaf9
spec: {}

----

**Observation**

No default project template is configured

**Recommendation**

Configure a default project template to enforce consistent settings across new projects

Refer to https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/html-single/building_applications/index#configuring-project-creation

Refer to https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/html-single/building_applications/index#quotas-setting-per-project

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== Kubeadmin User

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

[source, bash]
----
Secret 'kubeadmin' not found in 'kube-system' namespace
----

**Observation**

The kubeadmin user has been removed

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== Identity Provider Configuration

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, bash]
----
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/create-only: "true"
  creationTimestamp: "2025-04-13T07:55:14Z"
  generation: 2
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: 34bdd9cd-2ad6-4996-b4cd-21f09f96a111
  resourceVersion: "22974"
  uid: 24233435-e70f-4134-8d65-87494d13bdc5
spec:
  identityProviders:
  - htpasswd:
      fileData:
        name: htpasswd
    mappingMethod: claim
    name: htpasswd_provider
    type: HTPasswd

----

**Observation**

Identity providers are configured (HTPasswd), but no LDAP provider found

**Recommendation**

Configure a central identity provider (LDAP) for better integration with existing identity management systems

Refer to https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/html-single/authentication_and_authorization/index#configuring-ldap-identity-provider

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== Self Provisioner

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, bash]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2025-04-13T08:04:19Z"
  name: self-provisioners
  resourceVersion: "10360"
  uid: 3a723a90-563d-41fd-97df-074658750793
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: self-provisioner
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated:oauth

----

**Observation**

Self-provisioner role binding includes system:authenticated:oauth, allowing uncontrolled namespace creation

**Recommendation**

Remove the self-provisioner role from the system:authenticated:oauth group

Refer to https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/html-single/building_applications/index#disabling-project-self-provisioning_configuring-project-creation

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== Monitoring Storage

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, bash]
----
Failed to get detailed monitoring ConfigMap information
----

**Observation**

OpenShift monitoring components do not have persistent storage configured

**Recommendation**

Configure persistent storage for monitoring components

Refer to https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/html-single/monitoring/configuring-the-monitoring-stack

Refer to https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/html-single/monitoring/index#configuring_persistent_storage_configuring-the-monitoring-stack

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== User Workload Monitoring

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

[source, bash]
----
Failed to get detailed monitoring ConfigMap information
----

**Observation**

User workload monitoring is enabled

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== OpenShift Logging Installation

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

**Observation**

OpenShift Logging is not installed

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== OpenShift Logging Health

[cols="^"]
|===
|
{set:cellbgcolor:#A6B9BF}
Not Applicable
|===

**Observation**

OpenShift Logging is not installed

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== OpenShift Logging Storage

[cols="^"]
|===
|
{set:cellbgcolor:#A6B9BF}
Not Applicable
|===

**Observation**

OpenShift Logging is not installed

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== Log Forwarding

[cols="^"]
|===
|
{set:cellbgcolor:#A6B9BF}
Not Applicable
|===

**Observation**

OpenShift Logging is not installed

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== Logging Component Placement

[cols="^"]
|===
|
{set:cellbgcolor:#A6B9BF}
Not Applicable
|===

**Observation**

OpenShift Logging is not installed

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

== Service Monitors

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, bash]
----
ServiceMonitors found:

No user ServiceMonitors found

----

**Observation**

No ServiceMonitors found for application metrics monitoring

**Recommendation**

Create ServiceMonitors for your applications to collect custom metrics

Refer to https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/html-single/monitoring/index#specifying-how-a-service-is-monitored

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.17/

// Reset bgcolor for future tables
[grid=none,frame=none]
|===
|{set:cellbgcolor!}
|===

