= OpenShift Health Check Report

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Key

[cols="1,3", options=header]
|===
|Value
|Description

|
{set:cellbgcolor:#FF0000}
Changes Required
|
{set:cellbgcolor!}
Indicates Changes Required for system stability, subscription compliance, or other reason.

|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|
{set:cellbgcolor!}
Indicates Changes Recommended to align with recommended practices, but not urgently required

|
{set:cellbgcolor:#A6B9BF}
N/A
|
{set:cellbgcolor!}
No advise given on line item.  For line items which are data-only to provide context.

|
{set:cellbgcolor:#80E5FF}
Advisory
|
{set:cellbgcolor!}
No change required or recommended, but additional information provided.

|
{set:cellbgcolor:#00FF00}
No Change
|
{set:cellbgcolor!}
No change required. In alignment with recommended practices.

|
{set:cellbgcolor:#FFFFFF}
To Be Evaluated
|
{set:cellbgcolor!}
Not yet evaluated. Will appear only in draft copies.
|===

= Summary


[cols="1,2,2,3", options=header]
|===
|*Category*
|*Item Evaluated*
|*Observed Result*
|*Recommendation*

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/cni-network-plugin.item

// Category
|
{set:cellbgcolor!}
Networking

// Item Evaluated
a|
<<CNI Network Plugin>>

| Cluster is using the recommended CNI network plugin: OVNKubernetes 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/network-policy.item

// Category
|
{set:cellbgcolor!}
Networking

// Item Evaluated
a|
<<Network Policy>>

| Found 3 network policies in the cluster 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/ingress-controller.item

// Category
|
{set:cellbgcolor!}
Networking

// Item Evaluated
a|
<<Ingress Controller>>

| Ingress controller has 2 configuration issues 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/ingress-controller-placement.item

// Category
|
{set:cellbgcolor!}
Networking

// Item Evaluated
a|
<<Ingress Controller Placement>>

| Ingress controller is not configured to be placed on infrastructure nodes 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/ingress-controller-replica.item

// Category
|
{set:cellbgcolor!}
Network

// Item Evaluated
a|
<<Ingress Controller Replicas>>

| Ingress controller has insufficient replicas: 2 (recommended: >= 3) 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/default-ingress-certificate.item

// Category
|
{set:cellbgcolor!}
Networking

// Item Evaluated
a|
<<Default Ingress Certificate>>

| Custom certificate is properly configured for the default ingress controller 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/storage-classes.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
<<Storage Classes>>

| Default storage class 'ocs-external-storagecluster-ceph-rbd' is configured and RWX-capable storage is available 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/persistent-volumes.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
<<Persistent Volumes>>

| All 5 persistent volumes are healthy 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/storage-performance.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
<<Storage Performance>>

| No storage classes with explicit performance characteristics found 

|{set:cellbgcolor:#80E5FF}
Advisory


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/cluster-version.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Cluster Version>>

| Cluster version 4.18.7 is up to date 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/cluster-operators.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Cluster Operators>>

| All cluster operators are available 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/node-status.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Node Status>>

| All 5 nodes are ready 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/node-usage.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Node Usage>>

| All nodes are within resource usage thresholds 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/control-node-schedulable.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Control Plane Node Schedulability>>

| All control plane nodes are properly configured to prevent regular workloads 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/infrastructure-nodes.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Infrastructure Nodes>>

| No dedicated infrastructure nodes found 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/infra-machine-config-pool.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Infrastructure Machine Config Pool>>

| No dedicated infrastructure machine config pool found 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/infrastructure-provider.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Infrastructure Provider>>

| Infrastructure provider type: BareMetal 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/installation-type.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Installation Type>>

| Installation type: Likely IPI (has machinesets but missing confirming configmap) 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/workload-off-infra-nodes.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Workloads on Infrastructure Nodes>>

| No dedicated infrastructure nodes found in the cluster 

|{set:cellbgcolor:#A6B9BF}
Not Applicable


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/proxy-settings.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<OpenShift Proxy Settings>>

| OpenShift Proxy is not configured 

|{set:cellbgcolor:#A6B9BF}
Not Applicable


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/infra-taints.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Infrastructure Taints>>

| No infrastructure nodes found in the cluster 

|{set:cellbgcolor:#A6B9BF}
Not Applicable


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/kubelet-garbage-collection.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Kubelet Garbage Collection>>

| No custom kubelet garbage collection configuration found (using defaults) 

|{set:cellbgcolor:#80E5FF}
Advisory


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/default-node-schedule.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Default Node Schedule>>

| No custom namespace node selectors are configured 

|{set:cellbgcolor:#80E5FF}
Advisory


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/application-probes.item

// Category
|
{set:cellbgcolor!}
Applications

// Item Evaluated
a|
<<Application Probes>>

| Many user workloads are missing probes: 100.0% missing readiness probes, 50.0% missing liveness probes 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/resource-quotas.item

// Category
|
{set:cellbgcolor!}
Applications

// Item Evaluated
a|
<<Resource Quotas>>

| Only 0.0% of user namespaces (0 out of 3) have both resource quotas and limit ranges configured 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/emptydir-volumes.item

// Category
|
{set:cellbgcolor!}
Applications

// Item Evaluated
a|
<<EmptyDir Volumes>>

| No user workloads are using emptyDir volumes 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/limit-range.item

// Category
|
{set:cellbgcolor!}
App Dev

// Item Evaluated
a|
<<LimitRange Configuration>>

| No namespaces have LimitRange configured 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/cluster-default-scc.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<Default Security Context Constraint>>

| Default security context constraint (restricted) has not been modified 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/elevated-privileges.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<Elevated Privileges>>

| No user workloads using privileged containers were found 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/etcd-encryption.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<ETCD Encryption>>

| ETCD encryption is not enabled 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/etcd-backup.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<ETCD Backup>>

| No CronJobs found that might be backing up etcd 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/etcd-health.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<ETCD Health>>

| ETCD cluster is healthy 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/default-project-template.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<Default Project Template>>

| No default project template is configured 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/kubeadmin-user.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<Kubeadmin User>>

| The kubeadmin user has been removed 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/identity-provider.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<Identity Provider Configuration>>

| Identity providers are configured (HTPasswd), but no LDAP provider found 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/self-provisioner.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<Self Provisioner>>

| Self-provisioner role binding includes system:authenticated:oauth, allowing uncontrolled namespace creation 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/monitoring-storage.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<Monitoring Storage>>

| OpenShift monitoring components do not have persistent storage configured 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/user-workload-monitoring.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<User Workload Monitoring>>

| User workload monitoring is enabled 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/logging-install.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<OpenShift Logging Installation>>

| OpenShift Logging is not installed 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/logging-health.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<OpenShift Logging Health>>

| OpenShift Logging is not installed 

|{set:cellbgcolor:#A6B9BF}
Not Applicable


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/logging-storage.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<OpenShift Logging Storage>>

| OpenShift Logging is not installed 

|{set:cellbgcolor:#A6B9BF}
Not Applicable


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/logging-forwarder.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<Log Forwarding>>

| OpenShift Logging is not installed 

|{set:cellbgcolor:#A6B9BF}
Not Applicable


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/logging-placement.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<Logging Component Placement>>

| OpenShift Logging is not installed 

|{set:cellbgcolor:#A6B9BF}
Not Applicable


// ------------------------ITEM END

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/service-monitors.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<Service Monitors>>

| No ServiceMonitors found for application metrics monitoring 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END

|===

<<<

{set:cellbgcolor!}

# Network

[cols="1,2,2,3", options=header]
|===
|*Category*
|*Item Evaluated*
|*Observed Result*
|*Recommendation*

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/cni-network-plugin.item

// Category
|
{set:cellbgcolor!}
Networking

// Item Evaluated
a|
<<CNI Network Plugin>>

| Cluster is using the recommended CNI network plugin: OVNKubernetes 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/network-policy.item

// Category
|
{set:cellbgcolor!}
Networking

// Item Evaluated
a|
<<Network Policy>>

| Found 3 network policies in the cluster 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/ingress-controller.item

// Category
|
{set:cellbgcolor!}
Networking

// Item Evaluated
a|
<<Ingress Controller>>

| Ingress controller has 2 configuration issues 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/ingress-controller-placement.item

// Category
|
{set:cellbgcolor!}
Networking

// Item Evaluated
a|
<<Ingress Controller Placement>>

| Ingress controller is not configured to be placed on infrastructure nodes 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/ingress-controller-replica.item

// Category
|
{set:cellbgcolor!}
Network

// Item Evaluated
a|
<<Ingress Controller Replicas>>

| Ingress controller has insufficient replicas: 2 (recommended: >= 3) 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/default-ingress-certificate.item

// Category
|
{set:cellbgcolor!}
Networking

// Item Evaluated
a|
<<Default Ingress Certificate>>

| Custom certificate is properly configured for the default ingress controller 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
|===

<<<

{set:cellbgcolor!}

# Storage

[cols="1,2,2,3", options=header]
|===
|*Category*
|*Item Evaluated*
|*Observed Result*
|*Recommendation*

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/storage-classes.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
<<Storage Classes>>

| Default storage class 'ocs-external-storagecluster-ceph-rbd' is configured and RWX-capable storage is available 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/persistent-volumes.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
<<Persistent Volumes>>

| All 5 persistent volumes are healthy 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/storage-performance.item

// Category
|
{set:cellbgcolor!}
Storage

// Item Evaluated
a|
<<Storage Performance>>

| No storage classes with explicit performance characteristics found 

|{set:cellbgcolor:#80E5FF}
Advisory


// ------------------------ITEM END
|===

<<<

{set:cellbgcolor!}

# Cluster Config

[cols="1,2,2,3", options=header]
|===
|*Category*
|*Item Evaluated*
|*Observed Result*
|*Recommendation*

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/cluster-version.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Cluster Version>>

| Cluster version 4.18.7 is up to date 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/cluster-operators.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Cluster Operators>>

| All cluster operators are available 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/node-status.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Node Status>>

| All 5 nodes are ready 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/node-usage.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Node Usage>>

| All nodes are within resource usage thresholds 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/control-node-schedulable.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Control Plane Node Schedulability>>

| All control plane nodes are properly configured to prevent regular workloads 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/infrastructure-nodes.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Infrastructure Nodes>>

| No dedicated infrastructure nodes found 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/infra-machine-config-pool.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Infrastructure Machine Config Pool>>

| No dedicated infrastructure machine config pool found 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/infrastructure-provider.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Infrastructure Provider>>

| Infrastructure provider type: BareMetal 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/installation-type.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Installation Type>>

| Installation type: Likely IPI (has machinesets but missing confirming configmap) 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/workload-off-infra-nodes.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Workloads on Infrastructure Nodes>>

| No dedicated infrastructure nodes found in the cluster 

|{set:cellbgcolor:#A6B9BF}
Not Applicable


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/proxy-settings.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<OpenShift Proxy Settings>>

| OpenShift Proxy is not configured 

|{set:cellbgcolor:#A6B9BF}
Not Applicable


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/infra-taints.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Infrastructure Taints>>

| No infrastructure nodes found in the cluster 

|{set:cellbgcolor:#A6B9BF}
Not Applicable


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/kubelet-garbage-collection.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Kubelet Garbage Collection>>

| No custom kubelet garbage collection configuration found (using defaults) 

|{set:cellbgcolor:#80E5FF}
Advisory


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/default-node-schedule.item

// Category
|
{set:cellbgcolor!}
Cluster Config

// Item Evaluated
a|
<<Default Node Schedule>>

| No custom namespace node selectors are configured 

|{set:cellbgcolor:#80E5FF}
Advisory


// ------------------------ITEM END
|===

<<<

{set:cellbgcolor!}

# App Dev

[cols="1,2,2,3", options=header]
|===
|*Category*
|*Item Evaluated*
|*Observed Result*
|*Recommendation*

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/application-probes.item

// Category
|
{set:cellbgcolor!}
Applications

// Item Evaluated
a|
<<Application Probes>>

| Many user workloads are missing probes: 100.0% missing readiness probes, 50.0% missing liveness probes 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/resource-quotas.item

// Category
|
{set:cellbgcolor!}
Applications

// Item Evaluated
a|
<<Resource Quotas>>

| Only 0.0% of user namespaces (0 out of 3) have both resource quotas and limit ranges configured 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/emptydir-volumes.item

// Category
|
{set:cellbgcolor!}
Applications

// Item Evaluated
a|
<<EmptyDir Volumes>>

| No user workloads are using emptyDir volumes 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/limit-range.item

// Category
|
{set:cellbgcolor!}
App Dev

// Item Evaluated
a|
<<LimitRange Configuration>>

| No namespaces have LimitRange configured 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END
|===

<<<

{set:cellbgcolor!}

# Security

[cols="1,2,2,3", options=header]
|===
|*Category*
|*Item Evaluated*
|*Observed Result*
|*Recommendation*

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/cluster-default-scc.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<Default Security Context Constraint>>

| Default security context constraint (restricted) has not been modified 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/elevated-privileges.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<Elevated Privileges>>

| No user workloads using privileged containers were found 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/etcd-encryption.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<ETCD Encryption>>

| ETCD encryption is not enabled 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/etcd-backup.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<ETCD Backup>>

| No CronJobs found that might be backing up etcd 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/etcd-health.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<ETCD Health>>

| ETCD cluster is healthy 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/default-project-template.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<Default Project Template>>

| No default project template is configured 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/kubeadmin-user.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<Kubeadmin User>>

| The kubeadmin user has been removed 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/identity-provider.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<Identity Provider Configuration>>

| Identity providers are configured (HTPasswd), but no LDAP provider found 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/self-provisioner.item

// Category
|
{set:cellbgcolor!}
Security

// Item Evaluated
a|
<<Self Provisioner>>

| Self-provisioner role binding includes system:authenticated:oauth, allowing uncontrolled namespace creation 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END
|===

<<<

{set:cellbgcolor!}

# Op-Ready

[cols="1,2,2,3", options=header]
|===
|*Category*
|*Item Evaluated*
|*Observed Result*
|*Recommendation*

// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/monitoring-storage.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<Monitoring Storage>>

| OpenShift monitoring components do not have persistent storage configured 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/user-workload-monitoring.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<User Workload Monitoring>>

| User workload monitoring is enabled 

|{set:cellbgcolor:#00FF00}
No Change


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/logging-install.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<OpenShift Logging Installation>>

| OpenShift Logging is not installed 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/logging-health.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<OpenShift Logging Health>>

| OpenShift Logging is not installed 

|{set:cellbgcolor:#A6B9BF}
Not Applicable


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/logging-storage.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<OpenShift Logging Storage>>

| OpenShift Logging is not installed 

|{set:cellbgcolor:#A6B9BF}
Not Applicable


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/logging-forwarder.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<Log Forwarding>>

| OpenShift Logging is not installed 

|{set:cellbgcolor:#A6B9BF}
Not Applicable


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/logging-placement.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<Logging Component Placement>>

| OpenShift Logging is not installed 

|{set:cellbgcolor:#A6B9BF}
Not Applicable


// ------------------------ITEM END
// ------------------------ITEM START
// ----ITEM SOURCE:  ./content/healthcheck-items/service-monitors.item

// Category
|
{set:cellbgcolor!}
Op-Ready

// Item Evaluated
a|
<<Service Monitors>>

| No ServiceMonitors found for application metrics monitoring 

|{set:cellbgcolor:#FEFE20}
Changes Recommended


// ------------------------ITEM END
|===

<<<

{set:cellbgcolor!}

== CNI Network Plugin

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

[source, bash]
----
apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: Network
  metadata:
    creationTimestamp: "2025-04-14T04:17:25Z"
    generation: 5
    name: cluster
    resourceVersion: "254599"
    uid: 9ec68f6a-cfd3-4eed-8e32-0de6666631dd
  spec:
    clusterNetwork:
    - cidr: 10.132.0.0/14
      hostPrefix: 23
    externalIP:
      policy: {}
    networkDiagnostics:
      mode: ""
      sourcePlacement: {}
      targetPlacement: {}
    networkType: OVNKubernetes
    serviceNetwork:
    - 172.31.0.0/16
  status:
    clusterNetwork:
    - cidr: 10.132.0.0/14
      hostPrefix: 23
    clusterNetworkMTU: 1400
    conditions:
    - lastTransitionTime: "2025-04-14T13:24:39Z"
      message: ""
      observedGeneration: 0
      reason: AsExpected
      status: "True"
      type: NetworkDiagnosticsAvailable
    networkType: OVNKubernetes
    serviceNetwork:
    - 172.31.0.0/16
kind: List
metadata:
  resourceVersion: ""

----

**Observation**

Cluster is using the recommended CNI network plugin: OVNKubernetes

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Network Policy

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

[source, bash]
----
NAMESPACE            NAME                                       POD-SELECTOR                                               AGE
assisted-installer   assisted-installer-network-policy          <none>                                                     9h
openshift-gitops     openshift-gitops-redis-ha-network-policy   app.kubernetes.io/name=openshift-gitops-redis-ha-haproxy   8h
openshift-gitops     openshift-gitops-redis-network-policy      app.kubernetes.io/name=openshift-gitops-redis              8h

----

**Observation**

Found 3 network policies in the cluster

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Ingress Controller

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, bash]
----
Issues:
Ingress controller is not placed on dedicated infrastructure nodes
Ingress controller has insufficient replicas: 2 (recommended: >= 3)

apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  creationTimestamp: "2025-04-14T04:17:48Z"
  finalizers:
  - ingresscontroller.operator.openshift.io/finalizer-ingresscontroller
  generation: 3
  name: default
  namespace: openshift-ingress-operator
  resourceVersion: "261474"
  uid: a2337263-25ca-4c88-b2b2-a304ef6f193c
spec:
  clientTLS:
    clientCA:
      name: ""
    clientCertificatePolicy: ""
  defaultCertificate:
    name: cert-manager-ingress-cert
  endpointPublishingStrategy:
    type: HostNetwork
  httpCompression: {}
  httpEmptyRequestsPolicy: Respond
  httpErrorCodePages:
    name: ""
  idleConnectionTerminationPolicy: Deferred
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/worker: ""
  replicas: 2
  tuningOptions:
    reloadInterval: 0s
  unsupportedConfigOverrides: null
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2025-04-14T04:23:01Z"
    reason: Valid
    status: "True"
    type: Admitted
  - lastTransitionTime: "2025-04-14T13:25:26Z"
    message: The deployment has Available status condition set to True
    reason: DeploymentAvailable
    status: "True"
    type: DeploymentAvailable
  - lastTransitionTime: "2025-04-14T13:25:26Z"
    message: Minimum replicas requirement is met
    reason: DeploymentMinimumReplicasMet
    status: "True"
    type: DeploymentReplicasMinAvailable
  - lastTransitionTime: "2025-04-14T13:25:26Z"
    message: All replicas are available
    reason: DeploymentReplicasAvailable
    status: "True"
    type: DeploymentReplicasAllAvailable
  - lastTransitionTime: "2025-04-14T13:25:26Z"
    message: Deployment is not actively rolling out
    reason: DeploymentNotRollingOut
    status: "False"
    type: DeploymentRollingOut
  - lastTransitionTime: "2025-04-14T04:23:02Z"
    message: The configured endpoint publishing strategy does not include a managed
      load balancer
    reason: EndpointPublishingStrategyExcludesManagedLoadBalancer
    status: "False"
    type: LoadBalancerManaged
  - lastTransitionTime: "2025-04-14T04:23:02Z"
    message: LoadBalancer is not progressing
    reason: LoadBalancerNotProgressing
    status: "False"
    type: LoadBalancerProgressing
  - lastTransitionTime: "2025-04-14T04:23:02Z"
    message: No DNS zones are defined in the cluster dns config.
    reason: NoDNSZones
    status: "False"
    type: DNSManaged
  - lastTransitionTime: "2025-04-14T13:25:26Z"
    status: "True"
    type: Available
  - lastTransitionTime: "2025-04-14T13:25:26Z"
    status: "False"
    type: Progressing
  - lastTransitionTime: "2025-04-14T06:56:29Z"
    status: "False"
    type: Degraded
  - lastTransitionTime: "2025-04-14T04:23:02Z"
    message: IngressController is upgradeable.
    reason: Upgradeable
    status: "True"
    type: Upgradeable
  - lastTransitionTime: "2025-04-14T04:23:02Z"
    message: No evaluation condition is detected.
    reason: NoEvaluationCondition
    status: "False"
    type: EvaluationConditionsDetected
  - lastTransitionTime: "2025-04-14T04:34:56Z"
    message: Canary route checks for the default ingress controller are successful
    reason: CanaryChecksSucceeding
    status: "True"
    type: CanaryChecksSucceeding
  domain: apps.cluster-mt277.dynamic.redhatworkshops.io
  endpointPublishingStrategy:
    hostNetwork:
      httpPort: 80
      httpsPort: 443
      protocol: TCP
      statsPort: 1936
    type: HostNetwork
  observedGeneration: 3
  selector: ingresscontroller.operator.openshift.io/deployment-ingresscontroller=default
  tlsProfile:
    ciphers:
    - ECDHE-ECDSA-AES128-GCM-SHA256
    - ECDHE-RSA-AES128-GCM-SHA256
    - ECDHE-ECDSA-AES256-GCM-SHA384
    - ECDHE-RSA-AES256-GCM-SHA384
    - ECDHE-ECDSA-CHACHA20-POLY1305
    - ECDHE-RSA-CHACHA20-POLY1305
    - DHE-RSA-AES128-GCM-SHA256
    - DHE-RSA-AES256-GCM-SHA384
    - TLS_AES_128_GCM_SHA256
    - TLS_AES_256_GCM_SHA384
    - TLS_CHACHA20_POLY1305_SHA256
    minTLSVersion: VersionTLS12

----

**Observation**

Ingress controller has 2 configuration issues

**Recommendation**

Configure the ingress controller to run on dedicated infrastructure nodes

Refer to https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/html-single/networking/index#nw-ingress-controller-configuration-parameters_configuring-ingress

Increase the number of ingress controller replicas to at least 3 for high availability

Refer to https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/html-single/networking/index#configuring-ingress

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Ingress Controller Placement

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, bash]
----
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  creationTimestamp: "2025-04-14T04:17:48Z"
  finalizers:
  - ingresscontroller.operator.openshift.io/finalizer-ingresscontroller
  generation: 3
  name: default
  namespace: openshift-ingress-operator
  resourceVersion: "261474"
  uid: a2337263-25ca-4c88-b2b2-a304ef6f193c
spec:
  clientTLS:
    clientCA:
      name: ""
    clientCertificatePolicy: ""
  defaultCertificate:
    name: cert-manager-ingress-cert
  endpointPublishingStrategy:
    type: HostNetwork
  httpCompression: {}
  httpEmptyRequestsPolicy: Respond
  httpErrorCodePages:
    name: ""
  idleConnectionTerminationPolicy: Deferred
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/worker: ""
  replicas: 2
  tuningOptions:
    reloadInterval: 0s
  unsupportedConfigOverrides: null
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2025-04-14T04:23:01Z"
    reason: Valid
    status: "True"
    type: Admitted
  - lastTransitionTime: "2025-04-14T13:25:26Z"
    message: The deployment has Available status condition set to True
    reason: DeploymentAvailable
    status: "True"
    type: DeploymentAvailable
  - lastTransitionTime: "2025-04-14T13:25:26Z"
    message: Minimum replicas requirement is met
    reason: DeploymentMinimumReplicasMet
    status: "True"
    type: DeploymentReplicasMinAvailable
  - lastTransitionTime: "2025-04-14T13:25:26Z"
    message: All replicas are available
    reason: DeploymentReplicasAvailable
    status: "True"
    type: DeploymentReplicasAllAvailable
  - lastTransitionTime: "2025-04-14T13:25:26Z"
    message: Deployment is not actively rolling out
    reason: DeploymentNotRollingOut
    status: "False"
    type: DeploymentRollingOut
  - lastTransitionTime: "2025-04-14T04:23:02Z"
    message: The configured endpoint publishing strategy does not include a managed
      load balancer
    reason: EndpointPublishingStrategyExcludesManagedLoadBalancer
    status: "False"
    type: LoadBalancerManaged
  - lastTransitionTime: "2025-04-14T04:23:02Z"
    message: LoadBalancer is not progressing
    reason: LoadBalancerNotProgressing
    status: "False"
    type: LoadBalancerProgressing
  - lastTransitionTime: "2025-04-14T04:23:02Z"
    message: No DNS zones are defined in the cluster dns config.
    reason: NoDNSZones
    status: "False"
    type: DNSManaged
  - lastTransitionTime: "2025-04-14T13:25:26Z"
    status: "True"
    type: Available
  - lastTransitionTime: "2025-04-14T13:25:26Z"
    status: "False"
    type: Progressing
  - lastTransitionTime: "2025-04-14T06:56:29Z"
    status: "False"
    type: Degraded
  - lastTransitionTime: "2025-04-14T04:23:02Z"
    message: IngressController is upgradeable.
    reason: Upgradeable
    status: "True"
    type: Upgradeable
  - lastTransitionTime: "2025-04-14T04:23:02Z"
    message: No evaluation condition is detected.
    reason: NoEvaluationCondition
    status: "False"
    type: EvaluationConditionsDetected
  - lastTransitionTime: "2025-04-14T04:34:56Z"
    message: Canary route checks for the default ingress controller are successful
    reason: CanaryChecksSucceeding
    status: "True"
    type: CanaryChecksSucceeding
  domain: apps.cluster-mt277.dynamic.redhatworkshops.io
  endpointPublishingStrategy:
    hostNetwork:
      httpPort: 80
      httpsPort: 443
      protocol: TCP
      statsPort: 1936
    type: HostNetwork
  observedGeneration: 3
  selector: ingresscontroller.operator.openshift.io/deployment-ingresscontroller=default
  tlsProfile:
    ciphers:
    - ECDHE-ECDSA-AES128-GCM-SHA256
    - ECDHE-RSA-AES128-GCM-SHA256
    - ECDHE-ECDSA-AES256-GCM-SHA384
    - ECDHE-RSA-AES256-GCM-SHA384
    - ECDHE-ECDSA-CHACHA20-POLY1305
    - ECDHE-RSA-CHACHA20-POLY1305
    - DHE-RSA-AES128-GCM-SHA256
    - DHE-RSA-AES256-GCM-SHA384
    - TLS_AES_128_GCM_SHA256
    - TLS_AES_256_GCM_SHA384
    - TLS_CHACHA20_POLY1305_SHA256
    minTLSVersion: VersionTLS12

----

**Observation**

Ingress controller is not configured to be placed on infrastructure nodes

**Recommendation**

Configure the ingress controller to be placed on infrastructure nodes using the node-role.kubernetes.io/infra label

Refer to the documentation at https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/html-single/networking/index#nw-ingress-controller-configuration-parameters_configuring-ingress

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Ingress Controller Replicas

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, bash]
----
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  creationTimestamp: "2025-04-14T04:17:48Z"
  finalizers:
  - ingresscontroller.operator.openshift.io/finalizer-ingresscontroller
  generation: 3
  name: default
  namespace: openshift-ingress-operator
  resourceVersion: "261474"
  uid: a2337263-25ca-4c88-b2b2-a304ef6f193c
spec:
  clientTLS:
    clientCA:
      name: ""
    clientCertificatePolicy: ""
  defaultCertificate:
    name: cert-manager-ingress-cert
  endpointPublishingStrategy:
    type: HostNetwork
  httpCompression: {}
  httpEmptyRequestsPolicy: Respond
  httpErrorCodePages:
    name: ""
  idleConnectionTerminationPolicy: Deferred
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/worker: ""
  replicas: 2
  tuningOptions:
    reloadInterval: 0s
  unsupportedConfigOverrides: null
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2025-04-14T04:23:01Z"
    reason: Valid
    status: "True"
    type: Admitted
  - lastTransitionTime: "2025-04-14T13:25:26Z"
    message: The deployment has Available status condition set to True
    reason: DeploymentAvailable
    status: "True"
    type: DeploymentAvailable
  - lastTransitionTime: "2025-04-14T13:25:26Z"
    message: Minimum replicas requirement is met
    reason: DeploymentMinimumReplicasMet
    status: "True"
    type: DeploymentReplicasMinAvailable
  - lastTransitionTime: "2025-04-14T13:25:26Z"
    message: All replicas are available
    reason: DeploymentReplicasAvailable
    status: "True"
    type: DeploymentReplicasAllAvailable
  - lastTransitionTime: "2025-04-14T13:25:26Z"
    message: Deployment is not actively rolling out
    reason: DeploymentNotRollingOut
    status: "False"
    type: DeploymentRollingOut
  - lastTransitionTime: "2025-04-14T04:23:02Z"
    message: The configured endpoint publishing strategy does not include a managed
      load balancer
    reason: EndpointPublishingStrategyExcludesManagedLoadBalancer
    status: "False"
    type: LoadBalancerManaged
  - lastTransitionTime: "2025-04-14T04:23:02Z"
    message: LoadBalancer is not progressing
    reason: LoadBalancerNotProgressing
    status: "False"
    type: LoadBalancerProgressing
  - lastTransitionTime: "2025-04-14T04:23:02Z"
    message: No DNS zones are defined in the cluster dns config.
    reason: NoDNSZones
    status: "False"
    type: DNSManaged
  - lastTransitionTime: "2025-04-14T13:25:26Z"
    status: "True"
    type: Available
  - lastTransitionTime: "2025-04-14T13:25:26Z"
    status: "False"
    type: Progressing
  - lastTransitionTime: "2025-04-14T06:56:29Z"
    status: "False"
    type: Degraded
  - lastTransitionTime: "2025-04-14T04:23:02Z"
    message: IngressController is upgradeable.
    reason: Upgradeable
    status: "True"
    type: Upgradeable
  - lastTransitionTime: "2025-04-14T04:23:02Z"
    message: No evaluation condition is detected.
    reason: NoEvaluationCondition
    status: "False"
    type: EvaluationConditionsDetected
  - lastTransitionTime: "2025-04-14T04:34:56Z"
    message: Canary route checks for the default ingress controller are successful
    reason: CanaryChecksSucceeding
    status: "True"
    type: CanaryChecksSucceeding
  domain: apps.cluster-mt277.dynamic.redhatworkshops.io
  endpointPublishingStrategy:
    hostNetwork:
      httpPort: 80
      httpsPort: 443
      protocol: TCP
      statsPort: 1936
    type: HostNetwork
  observedGeneration: 3
  selector: ingresscontroller.operator.openshift.io/deployment-ingresscontroller=default
  tlsProfile:
    ciphers:
    - ECDHE-ECDSA-AES128-GCM-SHA256
    - ECDHE-RSA-AES128-GCM-SHA256
    - ECDHE-ECDSA-AES256-GCM-SHA384
    - ECDHE-RSA-AES256-GCM-SHA384
    - ECDHE-ECDSA-CHACHA20-POLY1305
    - ECDHE-RSA-CHACHA20-POLY1305
    - DHE-RSA-AES128-GCM-SHA256
    - DHE-RSA-AES256-GCM-SHA384
    - TLS_AES_128_GCM_SHA256
    - TLS_AES_256_GCM_SHA384
    - TLS_CHACHA20_POLY1305_SHA256
    minTLSVersion: VersionTLS12

----

**Observation**

Ingress controller has insufficient replicas: 2 (recommended: >= 3)

**Recommendation**

Increase the number of ingress controller replicas to at least 3 for high availability

Refer to https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/html-single/networking/index#configuring-ingress

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Default Ingress Certificate

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

[source, bash]
----
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  creationTimestamp: "2025-04-14T04:17:48Z"
  finalizers:
  - ingresscontroller.operator.openshift.io/finalizer-ingresscontroller
  generation: 3
  name: default
  namespace: openshift-ingress-operator
  resourceVersion: "261474"
  uid: a2337263-25ca-4c88-b2b2-a304ef6f193c
spec:
  clientTLS:
    clientCA:
      name: ""
    clientCertificatePolicy: ""
  defaultCertificate:
    name: cert-manager-ingress-cert
  endpointPublishingStrategy:
    type: HostNetwork
  httpCompression: {}
  httpEmptyRequestsPolicy: Respond
  httpErrorCodePages:
    name: ""
  idleConnectionTerminationPolicy: Deferred
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/worker: ""
  replicas: 2
  tuningOptions:
    reloadInterval: 0s
  unsupportedConfigOverrides: null
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2025-04-14T04:23:01Z"
    reason: Valid
    status: "True"
    type: Admitted
  - lastTransitionTime: "2025-04-14T13:25:26Z"
    message: The deployment has Available status condition set to True
    reason: DeploymentAvailable
    status: "True"
    type: DeploymentAvailable
  - lastTransitionTime: "2025-04-14T13:25:26Z"
    message: Minimum replicas requirement is met
    reason: DeploymentMinimumReplicasMet
    status: "True"
    type: DeploymentReplicasMinAvailable
  - lastTransitionTime: "2025-04-14T13:25:26Z"
    message: All replicas are available
    reason: DeploymentReplicasAvailable
    status: "True"
    type: DeploymentReplicasAllAvailable
  - lastTransitionTime: "2025-04-14T13:25:26Z"
    message: Deployment is not actively rolling out
    reason: DeploymentNotRollingOut
    status: "False"
    type: DeploymentRollingOut
  - lastTransitionTime: "2025-04-14T04:23:02Z"
    message: The configured endpoint publishing strategy does not include a managed
      load balancer
    reason: EndpointPublishingStrategyExcludesManagedLoadBalancer
    status: "False"
    type: LoadBalancerManaged
  - lastTransitionTime: "2025-04-14T04:23:02Z"
    message: LoadBalancer is not progressing
    reason: LoadBalancerNotProgressing
    status: "False"
    type: LoadBalancerProgressing
  - lastTransitionTime: "2025-04-14T04:23:02Z"
    message: No DNS zones are defined in the cluster dns config.
    reason: NoDNSZones
    status: "False"
    type: DNSManaged
  - lastTransitionTime: "2025-04-14T13:25:26Z"
    status: "True"
    type: Available
  - lastTransitionTime: "2025-04-14T13:25:26Z"
    status: "False"
    type: Progressing
  - lastTransitionTime: "2025-04-14T06:56:29Z"
    status: "False"
    type: Degraded
  - lastTransitionTime: "2025-04-14T04:23:02Z"
    message: IngressController is upgradeable.
    reason: Upgradeable
    status: "True"
    type: Upgradeable
  - lastTransitionTime: "2025-04-14T04:23:02Z"
    message: No evaluation condition is detected.
    reason: NoEvaluationCondition
    status: "False"
    type: EvaluationConditionsDetected
  - lastTransitionTime: "2025-04-14T04:34:56Z"
    message: Canary route checks for the default ingress controller are successful
    reason: CanaryChecksSucceeding
    status: "True"
    type: CanaryChecksSucceeding
  domain: apps.cluster-mt277.dynamic.redhatworkshops.io
  endpointPublishingStrategy:
    hostNetwork:
      httpPort: 80
      httpsPort: 443
      protocol: TCP
      statsPort: 1936
    type: HostNetwork
  observedGeneration: 3
  selector: ingresscontroller.operator.openshift.io/deployment-ingresscontroller=default
  tlsProfile:
    ciphers:
    - ECDHE-ECDSA-AES128-GCM-SHA256
    - ECDHE-RSA-AES128-GCM-SHA256
    - ECDHE-ECDSA-AES256-GCM-SHA384
    - ECDHE-RSA-AES256-GCM-SHA384
    - ECDHE-ECDSA-CHACHA20-POLY1305
    - ECDHE-RSA-CHACHA20-POLY1305
    - DHE-RSA-AES128-GCM-SHA256
    - DHE-RSA-AES256-GCM-SHA384
    - TLS_AES_128_GCM_SHA256
    - TLS_AES_256_GCM_SHA384
    - TLS_CHACHA20_POLY1305_SHA256
    minTLSVersion: VersionTLS12

----

**Observation**

Custom certificate is properly configured for the default ingress controller

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Storage Classes

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

[source, bash]
----
NAME                                             PROVISIONER                             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ocs-external-storagecluster-ceph-rbd (default)   openshift-storage.rbd.csi.ceph.com      Delete          WaitForFirstConsumer   true                   8h
ocs-external-storagecluster-ceph-rbd-immediate   openshift-storage.rbd.csi.ceph.com      Delete          Immediate              true                   8h
ocs-external-storagecluster-cephfs               openshift-storage.cephfs.csi.ceph.com   Delete          Immediate              true                   8h
openshift-storage.noobaa.io                      openshift-storage.noobaa.io/obc         Delete          Immediate              false                  8h

----

**Observation**

Default storage class 'ocs-external-storagecluster-ceph-rbd' is configured and RWX-capable storage is available

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Persistent Volumes

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

[source, bash]
----
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                                                STORAGECLASS                           VOLUMEATTRIBUTESCLASS   REASON   AGE   VOLUMEMODE
pvc-51a38cd6-26ba-4450-b17d-5203ccba7c1a   50Gi       RWO            Delete           Bound    openshift-storage/db-noobaa-db-pg-0                                  ocs-external-storagecluster-ceph-rbd   <unset>                          8h    Filesystem
pvc-975a902a-5649-49ad-897b-244022b7fab9   100Gi      RWO            Delete           Bound    openshift-image-registry/pvc-image-registry                          ocs-external-storagecluster-ceph-rbd   <unset>                          8h    Filesystem
pvc-a456aa10-5b93-4e76-91bf-7f91d28f7dbb   50Gi       RWO            Delete           Bound    openshift-storage/noobaa-default-backing-store-noobaa-pvc-53b59b55   ocs-external-storagecluster-ceph-rbd   <unset>                          8h    Filesystem
pvc-b0551d84-dc3a-49a2-9e02-5c03a9b0e7f5   50Gi       RWO            Delete           Bound    openshift-storage/noobaa-default-backing-store-noobaa-pvc-0c493605   ocs-external-storagecluster-ceph-rbd   <unset>                          8h    Filesystem
pvc-f5017196-e927-4280-ba81-daec7674e8f7   50Gi       RWO            Delete           Bound    openshift-storage/noobaa-default-backing-store-noobaa-pvc-1e5ada97   ocs-external-storagecluster-ceph-rbd   <unset>                          8h    Filesystem

----

**Observation**

All 5 persistent volumes are healthy

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Storage Performance

[cols="^"]
|===
|
{set:cellbgcolor:#80E5FF}
Advisory
|===

[source, bash]
----
Storage Class Details:
apiVersion: v1
items:
- allowVolumeExpansion: true
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    annotations:
      description: Provides RWO Filesystem volumes, and RWO and RWX Block volumes
      storageclass.kubernetes.io/is-default-class: "true"
    creationTimestamp: "2025-04-14T04:54:32Z"
    name: ocs-external-storagecluster-ceph-rbd
    resourceVersion: "34825"
    uid: e7545deb-181e-425d-aa71-26ccdf4b5b7e
  parameters:
    clusterID: openshift-storage
    csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
    csi.storage.k8s.io/controller-expand-secret-namespace: openshift-storage
    csi.storage.k8s.io/fstype: ext4
    csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
    csi.storage.k8s.io/node-stage-secret-namespace: openshift-storage
    csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
    csi.storage.k8s.io/provisioner-secret-namespace: openshift-storage
    imageFeatures: layering,deep-flatten,exclusive-lock,object-map,fast-diff
    imageFormat: "2"
    pool: ocpv-tenants
    volumeNamePrefix: ocp4-cluster-mt277-
  provisioner: openshift-storage.rbd.csi.ceph.com
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer
- allowVolumeExpansion: true
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    annotations:
      description: Provides RWO Filesystem volumes, and RWO and RWX Block volumes
      storageclass.kubernetes.io/is-default-class: "false"
    creationTimestamp: "2025-04-14T04:54:33Z"
    name: ocs-external-storagecluster-ceph-rbd-immediate
    resourceVersion: "34891"
    uid: d5fcc257-710c-4182-8dd8-8d63422bbec3
  parameters:
    clusterID: openshift-storage
    csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
    csi.storage.k8s.io/controller-expand-secret-namespace: openshift-storage
    csi.storage.k8s.io/fstype: ext4
    csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
    csi.storage.k8s.io/node-stage-secret-namespace: openshift-storage
    csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
    csi.storage.k8s.io/provisioner-secret-namespace: openshift-storage
    imageFeatures: layering,deep-flatten,exclusive-lock,object-map,fast-diff
    imageFormat: "2"
    pool: ocpv-tenants
    volumeNamePrefix: ocp4-cluster-mt277-
  provisioner: openshift-storage.rbd.csi.ceph.com
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
- allowVolumeExpansion: true
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    annotations:
      description: Provides RWO and RWX Filesystem volumes
    creationTimestamp: "2025-04-14T04:54:37Z"
    name: ocs-external-storagecluster-cephfs
    resourceVersion: "35005"
    uid: ec0ed070-4af6-42eb-90ad-8979181434fb
  parameters:
    clusterID: openshift-storage
    csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
    csi.storage.k8s.io/controller-expand-secret-namespace: openshift-storage
    csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
    csi.storage.k8s.io/node-stage-secret-namespace: openshift-storage
    csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
    csi.storage.k8s.io/provisioner-secret-namespace: openshift-storage
    fsName: ocs-storagecluster-cephfilesystem
    pool: ocs-storagecluster-cephfilesystem-data0
  provisioner: openshift-storage.cephfs.csi.ceph.com
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
- apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    annotations:
      description: Provides Object Bucket Claims (OBCs)
    creationTimestamp: "2025-04-14T04:56:33Z"
    name: openshift-storage.noobaa.io
    resourceVersion: "38340"
    uid: f2a09c29-dfaf-4af4-bae5-c9294dd16d18
  parameters:
    bucketclass: noobaa-default-bucket-class
  provisioner: openshift-storage.noobaa.io/obc
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
kind: List
metadata:
  resourceVersion: ""

----

**Observation**

No storage classes with explicit performance characteristics found

**Recommendation**

Consider defining storage classes with different performance tiers

Label storage classes with performance characteristics for better workload placement

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Cluster Version

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

[source, bash]
----
apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: ClusterVersion
  metadata:
    creationTimestamp: "2025-04-14T04:17:29Z"
    generation: 2
    name: version
    resourceVersion: "262275"
    uid: 3d37acfc-e65a-48fe-ac94-c487b2aebec0
  spec:
    channel: stable-4.18
    clusterID: 4dd33a11-ce10-4d52-b813-c474e67a64e2
  status:
    availableUpdates: null
    capabilities:
      enabledCapabilities:
      - Build
      - CSISnapshot
      - CloudControllerManager
      - CloudCredential
      - Console
      - DeploymentConfig
      - ImageRegistry
      - Ingress
      - Insights
      - MachineAPI
      - NodeTuning
      - OperatorLifecycleManager
      - OperatorLifecycleManagerV1
      - Storage
      - baremetal
      - marketplace
      - openshift-samples
      knownCapabilities:
      - Build
      - CSISnapshot
      - CloudControllerManager
      - CloudCredential
      - Console
      - DeploymentConfig
      - ImageRegistry
      - Ingress
      - Insights
      - MachineAPI
      - NodeTuning
      - OperatorLifecycleManager
      - OperatorLifecycleManagerV1
      - Storage
      - baremetal
      - marketplace
      - openshift-samples
    conditions:
    - lastTransitionTime: "2025-04-14T04:17:56Z"
      status: "True"
      type: RetrievedUpdates
    - lastTransitionTime: "2025-04-14T04:17:56Z"
      message: Capabilities match configured spec
      reason: AsExpected
      status: "False"
      type: ImplicitlyEnabledCapabilities
    - lastTransitionTime: "2025-04-14T04:17:56Z"
      message: Payload loaded version="4.18.7" image="quay.io/openshift-release-dev/ocp-release@sha256:91037938dc2ebc2732e7baa6eb4192fa4376abab19f0f545848a87ab7c91931d"
        architecture="amd64"
      reason: PayloadLoaded
      status: "True"
      type: ReleaseAccepted
    - lastTransitionTime: "2025-04-14T04:43:23Z"
      message: Done applying 4.18.7
      status: "True"
      type: Available
    - lastTransitionTime: "2025-04-14T13:26:57Z"
      status: "False"
      type: Failing
    - lastTransitionTime: "2025-04-14T04:43:23Z"
      message: Cluster version is 4.18.7
      status: "False"
      type: Progressing
    desired:
      channels:
      - candidate-4.18
      - candidate-4.19
      - eus-4.18
      - fast-4.18
      - stable-4.18
      image: quay.io/openshift-release-dev/ocp-release@sha256:91037938dc2ebc2732e7baa6eb4192fa4376abab19f0f545848a87ab7c91931d
      url: https://access.redhat.com/errata/RHBA-2025:3293
      version: 4.18.7
    history:
    - completionTime: "2025-04-14T04:43:23Z"
      image: quay.io/openshift-release-dev/ocp-release@sha256:91037938dc2ebc2732e7baa6eb4192fa4376abab19f0f545848a87ab7c91931d
      startedTime: "2025-04-14T04:17:56Z"
      state: Completed
      verified: false
      version: 4.18.7
    observedGeneration: 2
    versionHash: 0uK8H9Mg3jA=
kind: List
metadata:
  resourceVersion: ""

----

**Observation**

Cluster version 4.18.7 is up to date

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Cluster Operators

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

[source, bash]
----
NAME                                       VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
authentication                             4.18.7    True        False         False      2m22s   
baremetal                                  4.18.7    True        False         False      9h      
cloud-controller-manager                   4.18.7    True        False         False      9h      
cloud-credential                           4.18.7    True        False         False      9h      
cluster-autoscaler                         4.18.7    True        False         False      9h      
config-operator                            4.18.7    True        False         False      9h      
console                                    4.18.7    True        False         False      8h      
control-plane-machine-set                  4.18.7    True        False         False      9h      
csi-snapshot-controller                    4.18.7    True        False         False      9h      
dns                                        4.18.7    True        False         False      2m14s   
etcd                                       4.18.7    True        False         False      9h      
image-registry                             4.18.7    True        False         False      2m10s   
ingress                                    4.18.7    True        False         False      118s    
insights                                   4.18.7    True        False         False      9h      
kube-apiserver                             4.18.7    True        False         False      9h      
kube-controller-manager                    4.18.7    True        False         False      9h      
kube-scheduler                             4.18.7    True        False         False      9h      
kube-storage-version-migrator              4.18.7    True        False         False      6h31m   
machine-api                                4.18.7    True        False         False      8h      
machine-approver                           4.18.7    True        False         False      9h      
machine-config                             4.18.7    True        False         False      9h      
marketplace                                4.18.7    True        False         False      9h      
monitoring                                 4.18.7    True        False         False      8h      
network                                    4.18.7    True        False         False      9h      
node-tuning                                4.18.7    True        False         False      8h      
olm                                        4.18.7    True        False         False      6h31m   
openshift-apiserver                        4.18.7    True        False         False      2m28s   
openshift-controller-manager               4.18.7    True        False         False      6h31m   
openshift-samples                          4.18.7    True        False         False      8h      
operator-lifecycle-manager                 4.18.7    True        False         False      9h      
operator-lifecycle-manager-catalog         4.18.7    True        False         False      9h      
operator-lifecycle-manager-packageserver   4.18.7    True        False         False      6h31m   
service-ca                                 4.18.7    True        False         False      9h      
storage                                    4.18.7    True        False         False      9h      

----

**Observation**

All cluster operators are available

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Node Status

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

[source, bash]
----
NAME                            STATUS   ROLES                  AGE   VERSION
control-plane-cluster-mt277-1   Ready    control-plane,master   9h    v1.31.6
control-plane-cluster-mt277-2   Ready    control-plane,master   9h    v1.31.6
control-plane-cluster-mt277-3   Ready    control-plane,master   8h    v1.31.6
worker-cluster-mt277-1          Ready    worker                 8h    v1.31.6
worker-cluster-mt277-2          Ready    worker                 8h    v1.31.6

----

**Observation**

All 5 nodes are ready

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Node Usage

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

[source, bash]
----
NAME                            CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
control-plane-cluster-mt277-1   854m         3%     8084Mi          12%       
control-plane-cluster-mt277-2   935m         3%     10790Mi         17%       
control-plane-cluster-mt277-3   1317m        5%     7217Mi          11%       
worker-cluster-mt277-1          436m         5%     7697Mi          51%       
worker-cluster-mt277-2          464m         6%     9141Mi          61%       

----

**Observation**

All nodes are within resource usage thresholds

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Control Plane Node Schedulability

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

[source, bash]
----
NAME                            STATUS   ROLES                  AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                                                KERNEL-VERSION                 CONTAINER-RUNTIME
control-plane-cluster-mt277-1   Ready    control-plane,master   9h    v1.31.6   10.10.10.10   <none>        Red Hat Enterprise Linux CoreOS 418.94.202503241359-0   5.14.0-427.62.1.el9_4.x86_64   cri-o://1.31.6-3.rhaos4.18.gitfd32f99.el9
control-plane-cluster-mt277-2   Ready    control-plane,master   9h    v1.31.6   10.10.10.11   <none>        Red Hat Enterprise Linux CoreOS 418.94.202503241359-0   5.14.0-427.62.1.el9_4.x86_64   cri-o://1.31.6-3.rhaos4.18.gitfd32f99.el9
control-plane-cluster-mt277-3   Ready    control-plane,master   8h    v1.31.6   10.10.10.12   <none>        Red Hat Enterprise Linux CoreOS 418.94.202503241359-0   5.14.0-427.62.1.el9_4.x86_64   cri-o://1.31.6-3.rhaos4.18.gitfd32f99.el9

----

**Observation**

All control plane nodes are properly configured to prevent regular workloads

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Infrastructure Nodes

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

**Observation**

No dedicated infrastructure nodes found

**Recommendation**

Configure dedicated infrastructure nodes

Infrastructure nodes allow you to isolate infrastructure workloads to prevent incurring billing costs against subscription counts and to separate maintenance and management

Refer to https://access.redhat.com/solutions/5034771

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Infrastructure Machine Config Pool

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, bash]
----
NAME     CONFIG                                             UPDATED   UPDATING   DEGRADED   MACHINECOUNT   READYMACHINECOUNT   UPDATEDMACHINECOUNT   DEGRADEDMACHINECOUNT   AGE
master   rendered-master-5258cbcfc6f299ad85694dd8f61020cb   True      False      False      3              3                   3                     0                      9h
worker   rendered-worker-7b07462dbd9ee186868eaa9eb47ab324   True      False      False      2              2                   2                     0                      9h

----

**Observation**

No dedicated infrastructure machine config pool found

**Recommendation**

Create a dedicated infrastructure machine config pool

In a production deployment, it is recommended that you deploy at least three machine sets to hold infrastructure components

Refer to https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/html-single/machine_management/index#creating-infrastructure-machinesets

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Infrastructure Provider

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

[source, bash]
----
apiVersion: config.openshift.io/v1
kind: Infrastructure
metadata:
  creationTimestamp: "2025-04-14T04:17:24Z"
  generation: 1
  name: cluster
  resourceVersion: "532"
  uid: dbeb19b9-d76d-4482-8b7b-b99f0a61617b
spec:
  cloudConfig:
    name: ""
  platformSpec:
    baremetal:
      apiServerInternalIPs:
      - 10.10.10.100
      ingressIPs:
      - 10.10.10.101
      machineNetworks:
      - 10.10.10.0/24
    type: BareMetal
status:
  apiServerInternalURI: https://api-int.cluster-mt277.dynamic.redhatworkshops.io:6443
  apiServerURL: https://api.cluster-mt277.dynamic.redhatworkshops.io:6443
  controlPlaneTopology: HighlyAvailable
  cpuPartitioning: None
  etcdDiscoveryDomain: ""
  infrastructureName: cluster-mt277-tf9rp
  infrastructureTopology: HighlyAvailable
  platform: BareMetal
  platformStatus:
    baremetal:
      apiServerInternalIP: 10.10.10.100
      apiServerInternalIPs:
      - 10.10.10.100
      ingressIP: 10.10.10.101
      ingressIPs:
      - 10.10.10.101
      loadBalancer:
        type: OpenShiftManagedDefault
      machineNetworks:
      - 10.10.10.0/24
    type: BareMetal

----

**Observation**

Infrastructure provider type: BareMetal

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Installation Type

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

[source, bash]
----
Infrastructure Name: cluster-mt277-tf9rp

Installation Type: Likely Installer-Provisioned Infrastructure (IPI)

Machinesets present: true

apiVersion: config.openshift.io/v1
kind: Infrastructure
metadata:
  creationTimestamp: "2025-04-14T04:17:24Z"
  generation: 1
  name: cluster
  resourceVersion: "532"
  uid: dbeb19b9-d76d-4482-8b7b-b99f0a61617b
spec:
  cloudConfig:
    name: ""
  platformSpec:
    baremetal:
      apiServerInternalIPs:
      - 10.10.10.100
      ingressIPs:
      - 10.10.10.101
      machineNetworks:
      - 10.10.10.0/24
    type: BareMetal
status:
  apiServerInternalURI: https://api-int.cluster-mt277.dynamic.redhatworkshops.io:6443
  apiServerURL: https://api.cluster-mt277.dynamic.redhatworkshops.io:6443
  controlPlaneTopology: HighlyAvailable
  cpuPartitioning: None
  etcdDiscoveryDomain: ""
  infrastructureName: cluster-mt277-tf9rp
  infrastructureTopology: HighlyAvailable
  platform: BareMetal
  platformStatus:
    baremetal:
      apiServerInternalIP: 10.10.10.100
      apiServerInternalIPs:
      - 10.10.10.100
      ingressIP: 10.10.10.101
      ingressIPs:
      - 10.10.10.101
      loadBalancer:
        type: OpenShiftManagedDefault
      machineNetworks:
      - 10.10.10.0/24
    type: BareMetal

----

**Observation**

Installation type: Likely IPI (has machinesets but missing confirming configmap)

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Workloads on Infrastructure Nodes

[cols="^"]
|===
|
{set:cellbgcolor:#A6B9BF}
Not Applicable
|===

**Observation**

No dedicated infrastructure nodes found in the cluster

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== OpenShift Proxy Settings

[cols="^"]
|===
|
{set:cellbgcolor:#A6B9BF}
Not Applicable
|===

[source, bash]
----
apiVersion: config.openshift.io/v1
kind: Proxy
metadata:
  creationTimestamp: "2025-04-14T04:17:25Z"
  generation: 1
  name: cluster
  resourceVersion: "549"
  uid: 36a3c9e3-eb0b-435c-851f-088feeffd9ca
spec:
  trustedCA:
    name: ""
status: {}

----

**Observation**

OpenShift Proxy is not configured

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Infrastructure Taints

[cols="^"]
|===
|
{set:cellbgcolor:#A6B9BF}
Not Applicable
|===

**Observation**

No infrastructure nodes found in the cluster

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Kubelet Garbage Collection

[cols="^"]
|===
|
{set:cellbgcolor:#80E5FF}
Advisory
|===

[source, bash]
----
No custom kubelet configuration found

Machine Config Pools:
master worker
----

**Observation**

No custom kubelet garbage collection configuration found (using defaults)

**Recommendation**

Consider configuring kubelet garbage collection parameters for production environments

Refer to the documentation at https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/html-single/nodes/index#nodes-nodes-garbage-collection

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Default Node Schedule

[cols="^"]
|===
|
{set:cellbgcolor:#80E5FF}
Advisory
|===

[source, bash]
----
NAME                            STATUS   ROLES                  AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                                                KERNEL-VERSION                 CONTAINER-RUNTIME
control-plane-cluster-mt277-1   Ready    control-plane,master   9h    v1.31.6   10.10.10.10   <none>        Red Hat Enterprise Linux CoreOS 418.94.202503241359-0   5.14.0-427.62.1.el9_4.x86_64   cri-o://1.31.6-3.rhaos4.18.gitfd32f99.el9
control-plane-cluster-mt277-2   Ready    control-plane,master   9h    v1.31.6   10.10.10.11   <none>        Red Hat Enterprise Linux CoreOS 418.94.202503241359-0   5.14.0-427.62.1.el9_4.x86_64   cri-o://1.31.6-3.rhaos4.18.gitfd32f99.el9
control-plane-cluster-mt277-3   Ready    control-plane,master   8h    v1.31.6   10.10.10.12   <none>        Red Hat Enterprise Linux CoreOS 418.94.202503241359-0   5.14.0-427.62.1.el9_4.x86_64   cri-o://1.31.6-3.rhaos4.18.gitfd32f99.el9
worker-cluster-mt277-1          Ready    worker                 8h    v1.31.6   10.10.10.20   <none>        Red Hat Enterprise Linux CoreOS 418.94.202503241359-0   5.14.0-427.62.1.el9_4.x86_64   cri-o://1.31.6-3.rhaos4.18.gitfd32f99.el9
worker-cluster-mt277-2          Ready    worker                 8h    v1.31.6   10.10.10.21   <none>        Red Hat Enterprise Linux CoreOS 418.94.202503241359-0   5.14.0-427.62.1.el9_4.x86_64   cri-o://1.31.6-3.rhaos4.18.gitfd32f99.el9

----

**Observation**

No custom namespace node selectors are configured

**Recommendation**

Consider configuring namespace node selectors to control workload placement

Refer to the documentation at https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/html-single/nodes/index#nodes-scheduler-node-selectors

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Application Probes

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, bash]
----
Summary:
- Total user workloads: 2
- Workloads missing readiness probes: 2 (100.0%)
- Workloads missing liveness probes: 1 (50.0%)
- Workloads missing both probes: 1 (50.0%)

Affected namespaces:
- cert-manager

Affected workloads:
- Deployment 'cert-manager' in namespace 'cert-manager' is missing readiness probe
- Deployment 'cert-manager-cainjector' in namespace 'cert-manager' is missing both readiness and liveness probes


What are Readiness and Liveness Probes?

Readiness Probe: Determines if a container is ready to accept traffic. When a pod's readiness check fails, it is removed from service load balancers.

Liveness Probe: Determines if a container is still running as expected. When a liveness check fails, Kubernetes will restart the container.

Benefits of using probes:
- Prevents traffic from being sent to unready containers
- Automatically restarts unhealthy containers
- Improves application resilience and availability
- Facilitates smoother deployments and updates
- Provides better visibility into application health

----

**Observation**

Many user workloads are missing probes: 100.0% missing readiness probes, 50.0% missing liveness probes

**Recommendation**

Configure readiness and liveness probes for all user workloads

Follow the Kubernetes documentation on pod lifecycle and probes: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Resource Quotas

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, bash]
----
Summary:
- Total user namespaces: 3
- Namespaces with resource quotas: 0 (0.0%)
- Namespaces with limit ranges: 0 (0.0%)
- Namespaces with both: 0 (0.0%)

Namespaces without resource quotas:
- assisted-installer
- cert-manager
- cert-manager-operator

Namespaces without limit ranges:
- assisted-installer
- cert-manager
- cert-manager-operator

Namespaces without both:
- assisted-installer
- cert-manager
- cert-manager-operator


What are Resource Quotas and Limit Ranges?

Resource Quotas: Define the total amount of resources a namespace can use. They limit the total CPU, memory, and other resources that can be consumed by all pods in a namespace.

Limit Ranges: Define default resource limits and requests for containers in a namespace. They can also enforce minimum and maximum resource usage limits.

Benefits of using Resource Quotas and Limit Ranges:
- Prevent resource starvation by limiting the total resources a namespace can consume
- Ensure fair resource allocation across namespaces
- Protect against runaway applications that might consume all available resources
- Enforce resource constraints and prevent resource leaks
- Help with capacity planning and cost management

----

**Observation**

Only 0.0% of user namespaces (0 out of 3) have both resource quotas and limit ranges configured

**Recommendation**

Configure resource quotas and limit ranges for all user namespaces

Follow the Kubernetes documentation on resource quotas: https://kubernetes.io/docs/concepts/policy/resource-quotas/

Follow the Kubernetes documentation on limit ranges: https://kubernetes.io/docs/concepts/policy/limit-range/

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== EmptyDir Volumes

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

**Observation**

No user workloads are using emptyDir volumes

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== LimitRange Configuration

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

**Observation**

No namespaces have LimitRange configured

**Recommendation**

Configure LimitRange resources in your namespaces to control resource usage

Follow best practices for resource management: https://kubernetes.io/docs/concepts/policy/limit-range/

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Default Security Context Constraint

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

[source, bash]
----
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: null
apiVersion: security.openshift.io/v1
defaultAddCapabilities: null
fsGroup:
  type: MustRunAs
groups: []
kind: SecurityContextConstraints
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    kubernetes.io/description: restricted denies access to all host features and requires
      pods to be run with a UID, and SELinux context that are allocated to the namespace.
    release.openshift.io/create-only: "true"
  creationTimestamp: "2025-04-14T04:17:06Z"
  generation: 1
  name: restricted
  resourceVersion: "349"
  uid: 6ec350b8-a5b9-4f06-b9c7-7975237ecd0e
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities:
- KILL
- MKNOD
- SETUID
- SETGID
runAsUser:
  type: MustRunAsRange
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users: []
volumes:
- configMap
- csi
- downwardAPI
- emptyDir
- ephemeral
- persistentVolumeClaim
- projected
- secret

----

**Observation**

Default security context constraint (restricted) has not been modified

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Elevated Privileges

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

**Observation**

No user workloads using privileged containers were found

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== ETCD Encryption

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, bash]
----
apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: APIServer
  metadata:
    annotations:
      include.release.openshift.io/ibm-cloud-managed: "true"
      include.release.openshift.io/self-managed-high-availability: "true"
      oauth-apiserver.openshift.io/secure-token-storage: "true"
      release.openshift.io/create-only: "true"
    creationTimestamp: "2025-04-14T04:17:58Z"
    generation: 1
    name: cluster
    ownerReferences:
    - apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      name: version
      uid: 3d37acfc-e65a-48fe-ac94-c487b2aebec0
    resourceVersion: "891"
    uid: 3783f30a-5980-4bf8-bc89-2db06f380fc5
  spec:
    audit:
      profile: Default
kind: List
metadata:
  resourceVersion: ""

----

**Observation**

ETCD encryption is not enabled

**Recommendation**

Enable etcd encryption to protect sensitive data

Follow the documentation at https://docs.openshift.com/container-platform/latest/security/encrypting-etcd.html

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== ETCD Backup

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, bash]
----
ETCD Cluster Operator status:
NAME   VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
etcd   4.18.7    True        False         False      9h      

----

**Observation**

No CronJobs found that might be backing up etcd

**Recommendation**

Set up regular etcd backups to protect against data loss

Follow the documentation at https://docs.openshift.com/container-platform/latest/backup_and_restore/control_plane_backup_and_restore/backing-up-etcd.html

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== ETCD Health

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

[source, bash]
----
ETCD Operator Information:
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  creationTimestamp: "2025-04-14T04:17:56Z"
  generation: 1
  name: etcd
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: 3d37acfc-e65a-48fe-ac94-c487b2aebec0
  resourceVersion: "258944"
  uid: c5b91373-a1dd-4487-a0ea-c166e1bc7bfc
spec: {}
status:
  conditions:
  - lastTransitionTime: "2025-04-14T04:25:36Z"
    message: |-
      NodeControllerDegraded: All master nodes are ready
      EtcdMembersDegraded: No unhealthy members found
    reason: AsExpected
    status: "False"
    type: Degraded
  - lastTransitionTime: "2025-04-14T04:42:01Z"
    message: |-
      NodeInstallerProgressing: 3 nodes are at revision 10
      EtcdMembersProgressing: No unstarted etcd members found
    reason: AsExpected
    status: "False"
    type: Progressing
  - lastTransitionTime: "2025-04-14T04:24:07Z"
    message: |-
      StaticPodsAvailable: 3 nodes are active; 3 nodes are at revision 10
      EtcdMembersAvailable: 3 members are available
    reason: AsExpected
    status: "True"
    type: Available
  - lastTransitionTime: "2025-04-14T04:22:17Z"
    message: All is well
    reason: AsExpected
    status: "True"
    type: Upgradeable
  - lastTransitionTime: "2025-04-14T04:22:17Z"
    reason: NoData
    status: Unknown
    type: EvaluationConditionsDetected
  extension: null
  relatedObjects:
  - group: operator.openshift.io
    name: cluster
    resource: etcds
  - group: ""
    name: openshift-config
    resource: namespaces
  - group: ""
    name: openshift-config-managed
    resource: namespaces
  - group: ""
    name: openshift-etcd-operator
    resource: namespaces
  - group: ""
    name: openshift-etcd
    resource: namespaces
  versions:
  - name: raw-internal
    version: 4.18.7
  - name: etcd
    version: 4.18.7
  - name: operator
    version: 4.18.7


ETCD Pods Information:
NAME                                 READY   STATUS    RESTARTS   AGE
etcd-control-plane-cluster-mt277-1   5/5     Running   10         8h
etcd-control-plane-cluster-mt277-2   5/5     Running   10         8h
etcd-control-plane-cluster-mt277-3   5/5     Running   10         8h

----

**Observation**

ETCD cluster is healthy

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Default Project Template

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, bash]
----
apiVersion: config.openshift.io/v1
kind: Project
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/create-only: "true"
  creationTimestamp: "2025-04-14T04:18:18Z"
  generation: 1
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: 3d37acfc-e65a-48fe-ac94-c487b2aebec0
  resourceVersion: "1760"
  uid: bf689a39-4188-4f6d-b860-8d5e6102133b
spec: {}

----

**Observation**

No default project template is configured

**Recommendation**

Configure a default project template to enforce consistent settings across new projects

Refer to https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/html-single/building_applications/index#configuring-project-creation

Refer to https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/html-single/building_applications/index#quotas-setting-per-project

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Kubeadmin User

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

[source, bash]
----
Secret 'kubeadmin' not found in 'kube-system' namespace
----

**Observation**

The kubeadmin user has been removed

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Identity Provider Configuration

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, bash]
----
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/create-only: "true"
  creationTimestamp: "2025-04-14T04:18:16Z"
  generation: 2
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: 3d37acfc-e65a-48fe-ac94-c487b2aebec0
  resourceVersion: "29115"
  uid: c90de733-fe2a-4f44-a305-ea72d0f3d028
spec:
  identityProviders:
  - htpasswd:
      fileData:
        name: htpasswd
    mappingMethod: claim
    name: htpasswd_provider
    type: HTPasswd

----

**Observation**

Identity providers are configured (HTPasswd), but no LDAP provider found

**Recommendation**

Configure a central identity provider (LDAP) for better integration with existing identity management systems

Refer to https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/html-single/authentication_and_authorization/index#configuring-ldap-identity-provider

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Self Provisioner

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, bash]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2025-04-14T04:22:44Z"
  name: self-provisioners
  resourceVersion: "7550"
  uid: 012ce214-a42b-4114-85e4-519ae25b74d9
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: self-provisioner
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated:oauth

----

**Observation**

Self-provisioner role binding includes system:authenticated:oauth, allowing uncontrolled namespace creation

**Recommendation**

Remove the self-provisioner role from the system:authenticated:oauth group

Refer to https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/html-single/building_applications/index#disabling-project-self-provisioning_configuring-project-creation

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Monitoring Storage

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, bash]
----
Failed to get detailed monitoring ConfigMap information
----

**Observation**

OpenShift monitoring components do not have persistent storage configured

**Recommendation**

Configure persistent storage for monitoring components

Refer to https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/html-single/monitoring/configuring-the-monitoring-stack

Refer to https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/html-single/monitoring/index#configuring_persistent_storage_configuring-the-monitoring-stack

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== User Workload Monitoring

[cols="^"]
|===
|
{set:cellbgcolor:#00FF00}
No Change
|===

[source, bash]
----
Failed to get detailed monitoring ConfigMap information
----

**Observation**

User workload monitoring is enabled

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== OpenShift Logging Installation

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

**Observation**

OpenShift Logging is not installed

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== OpenShift Logging Health

[cols="^"]
|===
|
{set:cellbgcolor:#A6B9BF}
Not Applicable
|===

**Observation**

OpenShift Logging is not installed

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== OpenShift Logging Storage

[cols="^"]
|===
|
{set:cellbgcolor:#A6B9BF}
Not Applicable
|===

**Observation**

OpenShift Logging is not installed

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Log Forwarding

[cols="^"]
|===
|
{set:cellbgcolor:#A6B9BF}
Not Applicable
|===

**Observation**

OpenShift Logging is not installed

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Logging Component Placement

[cols="^"]
|===
|
{set:cellbgcolor:#A6B9BF}
Not Applicable
|===

**Observation**

OpenShift Logging is not installed

**Recommendation**

None

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

== Service Monitors

[cols="^"]
|===
|
{set:cellbgcolor:#FEFE20}
Changes Recommended
|===

[source, bash]
----
ServiceMonitors found:

No user ServiceMonitors found

----

**Observation**

No ServiceMonitors found for application metrics monitoring

**Recommendation**

Create ServiceMonitors for your applications to collect custom metrics

Refer to https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/html-single/monitoring/index#specifying-how-a-service-is-monitored

*Reference Link(s)*

* https://access.redhat.com/documentation/en-us/openshift_container_platform/4.18/

// Reset bgcolor for future tables
[grid=none,frame=none]
|===
|{set:cellbgcolor!}
|===

